### ISSUE TITLE
Should we provide an email history?

### ISSUE THREAD

**Issue by felixble** [4minitz/4minitz#10]
When finalizing a minute we send multiple emails to different recipients: we send action items to the responsible persons and information items to the persons who want to be informed about the meeting. I think it would be great if the user could have an overview which emails was sent successfully and which email couldn't be sent for any reason.

**Comment by derwok** [comment]
Sound like a great idea... it would be really annyoing, if the mail system is broken and the Finalize-user has no chance to find out...  :-(

On the other hand: maybe a messaging system is little to complex to add to the current story.
The InfoItems are always sent to all "visibleFor" users - and as such also to the moderator that does the Finalize job. So, if moderator sees this mail in his own inbox, mailing was at leas functionable.

I would vote for: let's generate some clear server-side logging for EMails in this story.
And put notification messages in a later story like here: https://trello.com/c/5NwQJ35D/97-notification-on-invitation-role-change
