### ISSUE TITLE
Topic titles are lost sometimes

### ISSUE THREAD

**Issue by migerh** [4minitz/4minitz#119]
On Travis CI this test

```
can add a responsible from drop-down that is an additional participant
```

of the Topics-Responsibles test suite is regularly failing.

The root cause seems to be that the topic title is lost:

![20160812194730501__additional-responsible-4](https://cloud.githubusercontent.com/assets/368715/17641218/8d4580d4-6116-11e6-95ce-63f58a854ef8.png)

Please note that the title is not only missing in the edit dialog but also in the topic list. It had to be there at some point, otherwise this topic would not have been added to the minutes.

**Comment by migerh** [comment]
I added the 0.6.0 milestone because this issue seems to be new while the test already existed for a while. Imho this issue should at least be analyzed and understood before releasing 0.6.0.

**Comment by migerh** [comment]
In build [#464](https://travis-ci.org/4minitz/4minitz/builds/152242452) another test failed that is related to topics:

    MeetingSeries complete Topic list
    1) copies all topics of the first minute to the parent series including both all info- and actionItems.
    
      Topic should have two items
      + expected - actual
      -1
      +2

**Comment by migerh** [comment]
The issue did not occur for quite some time now. Since no one ever observed this locally, maybe the issue was related to Travis and is fixed now?

**Comment by migerh** [comment]
Nobody is able to reproduce it and it did not occur on Travis CI for about 7 weeks. Nothing more to do here.

**Comment by derwok** [comment]
I could reproduce this issue in Safari on Mac. 
In Safari Browser perform these steps:
* Click "Add Topic"
* Do *nothing*(!) in the dialog
* Click "Save Topic"

=> A new topic with an empty subject is created.

**Comment by derwok** [comment]
We could not observe this issue in real usage. And I checked in current Mac Safari - it is not possible to save a topic without subject anymore.
=> Close.
