### ISSUE TITLE
Bring 4minitz.com to real "Continuous Deployment"

### ISSUE THREAD

**Issue by derwok** [4minitz/4minitz#127]
Currently we have CI via travis.

And we have "optimistic deployment" to 4minitz.com with every push to "/develop" or "/master" branch (no matter of Travis is currently green or red!).

Suggestion:
If-and-only-if travis CI runs green on /develop or /master, it should trigger 4minitz.com to pull github updates from /master or /develop branch respectively.

This could be considered as real continuous deployment.  ;-)

**Comment by migerh** [comment]
This might be useful:
https://docs.travis-ci.com/api
