### ISSUE TITLE
Details sometimes get "lost"

### ISSUE THREAD

**Issue by felixble** [4minitz/4minitz#142]
Sometimes editing existing details for action-/info-items removes them instead of saving the changes.

**Comment by derwok** [comment]
Reprodicible in **Safari** browser:
1. Add: a Topic => with Info Item => with one Detail (enter some text)
2. then add second detail (enter some text) - keep the cursor flashing inside the detail in "edit mode"
3. Press "Cmd+Tab" to swap to a different application, or optionally: change to a different browser tab
4. Switch back to 4Minitz - the second details is visible on screen, but not in edit mode anymore (seems like it is stored)
5. now klick on the second details text => **BAAMM** it's gone!

**Comment by felixble** [comment]
We avoid this problem by introducing a confirmation dialog which will be showed before details will be deleted.

Take care: Adding details and leaving the input field without entering any text should go silently.

**Comment by derwok** [comment]
Today this happend again... to an end-user.
(No "security question poped up).
With current "v0.8.0" - we will try to get "steps to reproduce".

**Comment by derwok** [comment]
Not seen anymore... Closing
