### ISSUE TITLE
Multiple Finalize Triggers

### ISSUE THREAD

**Issue by derwok** [4minitz/4minitz#144]
The dialog after click on "Finalize Minutes" asking if Action Items / Info Items shall be sent, sometimes is displayed too long on screen. No Feedback for user after pressing "Finalize" first time. So user clicked multiples times on "Finalize".

This leads to multiple sent Meeting Minutes Emails to all participants.
Even the version number is increased: V1, V2, V3, V4, V5...

**Comment by derwok** [comment]
![image](https://cloud.githubusercontent.com/assets/4393698/20212796/69f4585e-a805-11e6-85de-56c336d9d504.png)

**Comment by derwok** [comment]
![image](https://cloud.githubusercontent.com/assets/4393698/20212807/867cca74-a805-11e6-8ed3-b8eefc781a52.png)

**Comment by felixble** [comment]
#ACs
- [ ] forbid finalize workflow if a minute is already finalized
- [ ] disable finalize button after after first click
