### ISSUE TITLE
Improve user experience for finalize workflow

### ISSUE THREAD

**Issue by felixble** [4minitz/4minitz#145]
The process finalizing a minute and sending all mails takes some time. As a user I would like to see if there is something going on.

After clicking the Finalize-Button within the finaliz-dialog the dialog should close immediately. Then the "Finalize Minutes"-Button in the upper right corner of the minute should be replaced by a spinner item. If the finalize workflow is done we should show a success message and replace the spinner item again with the correct button.

**Comment by derwok** [comment]
With the current "show two messages" we can live for a while. 
Spinner only needed, if users demand one.  ;-)
