### ISSUE TITLE
Flash messages are gone away

### ISSUE THREAD

**Issue by felixble** [4minitz/4minitz#146]
After sending the agenda there is no success message anymore, for example.

**Comment by felixble** [comment]
@migerh Do you know when the function Router.onBeforeAction will be called? In the commit b39f91fbe93079e127f1db6eecb1327c409a246b you called the function FlashMessage.hide(). After removing this line the flash messages are there again... ;-)

Maybe we could remember the current page and call the hide()-Action only if the page will change ?

**Comment by migerh** [comment]
I assumed the flash messages are only meant for the current page. My assumption might be correct, depending on what you mean by "really" changed? If we are still on the same page, then why is the router invoked at all?

**Comment by felixble** [comment]
I noticed that the Router.onBeforeAction() will be called way more offen than the page will actually changed. This function will be called after the finalize dialog is closed for any - for me - unknown reason. I thought you have any idea what other events triggers this function.

**Comment by felixble** [comment]
Commit 67206856cf429e2b65ffc0b5f597cfdbec6e3064 made the FlashMessages visible again. Unfortunately they will sometimes be a bit too long visible e.g. if an error will be displayed because of an invalid login and the users logs in correctly within 5s. the flash message will be visibile until the 5s are completely over.
