### ISSUE TITLE
4Minitz is not runnable in a URL with subfolder like https://www.company.com/4minitz (ROOT_URL)

### ISSUE THREAD

**Issue by derwok** [4minitz/4minitz#152]
### Problem
If 4Minitz shall be reachable via a subfolder URL like https://www.company.com/4minitz this must be specified with the ROOT_URL environment variable. Nevertheless 4Minitz is not prepared to be reachable via non-"root" URL. Quite some errors show up...

### Steps to reproduce:
Launch 4Minitz locally in develop mode like so:

    export ROOT_URL=http://localhost:3100/4minitz
    meteor run --port 3100 --settings ./settings.json

Open WebApp in Browser via http://localhost:3100/4minitz

### Errors:
1. The IronRouter seems not to respect the ROOT_URL. Iron:Router shows error: "Oops, looks like there's no route on the client or the server for url: http://localhost:3100/4minitz"
1. These URLs show in the browser console as 404 errors:
4minitz:34 GET http://localhost:3100/node_modules/eonasdan-bootstrap-datetimepicker/build/css/bootstrap-datetimepicker.min.css 
4minitz-at-mp.png:1 GET http://localhost:3100/4minitz-at-mp.png 404 (Not Found)
apple-touch-icon-120x120.png:1 GET http://localhost:3100/apple-touch-icon-120x120.png 404 (Not Found)

### First analysis
It seems Iron Router is not prepared to handle situations where ROOT_URL has a subfolder attached. At least there is an open Pull Request for this issue:
https://github.com/iron-meteor/iron-url/pull/17

**Comment by derwok** [comment]
FlowRouter[1] seems to officially support ROOT_URL with sub-folders.
See: https://github.com/kadirahq/flow-router#prefixed-paths

[1] https://github.com/kadirahq/flow-router

**Comment by migerh** [comment]
Began with migration to kadira:flow-router in dd88667cc. App should still be functional, a few things need some more work though (see the commit message).

**Comment by migerh** [comment]
57aeddbc08 implements proper handling of environments with ROOT_URL set.
