### ISSUE TITLE
Only one(!) minutes mail per finalize

### ISSUE THREAD

**Issue by derwok** [4minitz/4minitz#17]
The minutes mail on finalize shall be sent as "one" mail with all recepients in the "TO:" field.

This ensures
1.) one can see, who else got this mail
2.) one can "reply to all" to sent additional info to the group

This offers a lack of security in an untrusted environment => add config "trustedEnvironment": this will enable/disable this feature

**Comment by derwok** [comment]
After discussion:
Add a top-level key "trustedIntranetInstallation" = true/false to our settings.json.
If true => send cummulative EMails, if false send separate mails.
We may re-use this setting - e.g. on display of users in the user editor - and show their real-name / EMAil-address etc.

**Comment by felixble** [comment]
@derwok is it necessary to send the AIs to all responsible persons in one mail, too?
