### ISSUE TITLE
Handle LDAP server not reachable more graceful

### ISSUE THREAD

**Issue by derwok** [4minitz/4minitz#174]
When the configured LDAP server is not reachable, the server process exits with error level "1".

W20170108-17:10:19.776(1)? (STDERR) events.js:141
W20170108-17:10:19.778(1)? (STDERR)       throw er; // Unhandled 'error' event
W20170108-17:10:19.779(1)? (STDERR)       ^
W20170108-17:10:19.779(1)? (STDERR)
W20170108-17:10:19.779(1)? (STDERR) Error: connect ECONNREFUSED 212.204.89.242:636
W20170108-17:10:19.780(1)? (STDERR)     at Object.exports._errnoException (util.js:911:11)
W20170108-17:10:19.780(1)? (STDERR)     at exports._exceptionWithHostPort (util.js:934:20)
W20170108-17:10:19.781(1)? (STDERR)     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1076:14)
=> Exited with code: 1

We should take care for this situation and show a user front end message telling to call for admin help and try again later...

**Comment by migerh** [comment]
Reason: https://github.com/mcavage/node-ldapjs/issues/317

The ldap package we are using (https://github.com/JackAdams/meteor-accounts-ldap) should handle this by attaching an error event handler. I will prepare a patch and submit a pull request.

**Comment by migerh** [comment]
pull request is merged, ldap package updated:
https://github.com/JackAdams/meteor-accounts-ldap/pull/18
