### ISSUE TITLE
Omit current branch in about-dialog if there are no branch information available

### ISSUE THREAD

**Issue by felixble** [4minitz/4minitz#185]
If you started 4minitz in a directory where no git informations are available (e.g. in docker) then the about box displays question marks as current branch (Branch: ??? (???)). I think we should omit that information.
![bildschirmfoto 2017-02-19 um 13 20 55](https://cloud.githubusercontent.com/assets/8507319/23102251/47889c18-f6a6-11e6-8097-58c16cebe597.png)

**Comment by derwok** [comment]
I actually started on this topic by writing this information into package.json...
So I attach "myself" to this issue.  ;-)

**Comment by derwok** [comment]
Should be fixed with abcafcaa7a432e18f1bce863160a1000de77d0ae
