### ISSUE TITLE
 [v1.x] Warn on multiple editing of the same document

### ISSUE THREAD

**Issue by derwok** [4minitz/4minitz#194]
If a user starts editing an...
* existing meeting series meta data
* existing Topic
* existing Action/Info Item
* existing Detail
then...

- [ ] the document should be marked on editing by a user (user & timestamp)
- [ ] In case of existing edit mark the edit trigger button should show an warning message: "Warning: This document is currently edited by user XYZ since date/time" [Cancel] [Edit Anyway] (red button)
     - hint date/time formatting should use imports/helpers/date.js
- [ ] Cancel does not start editing - nothing happens
- [ ] "Edit Anyway" overwrites the user/date mark with new user/date mark and proceeds to edit the doc
- [ ] user/date mark should be removed if user cancels/OKs the edit action
- [ ] user/date mark should be removed if user signs out of 4Minitz
- [ ] user/date mark should be removed on "Finalize" of minutes
- [ ] On "Finalize" show warning if user/date mark exists
- [ ] Optionally: In case of edit mark the item should show an optical UI hint - e.g. a "red dashed border"
- [ ] Optionally: Cleanup user/date marks after timeout (const TIMEOUT = 5 hrs;)

OPEN POINT: Clarify if "edit mark" on doc locks also sub doc children

**Comment by felixble** [comment]
We should have in mind that requesting a document-lock could be denied by the server (if two users send a request at the very same time).

Additionally, we should think about a concept how to handle the edge case if the connection is lost.

**Comment by woestmannje** [comment]
Team estimation: 4d

**Comment by RobNeXX** [comment]
My Oppinion on "edit mark" on doc locks also sub doc children
We should not lock sub documents because those elements are independent

**Comment by derwok** [comment]
Works like a charm!
Closed.
