### ISSUE TITLE
"Re-Open" closed topics

### ISSUE THREAD

**Issue by felixble** [4minitz/4minitz#197]
As a user I would like to (re-)open an already existing topic which was closed in a previous minutes because I want to discuss the same topic again.

Scenario: We discussed a topic, e.g. "internal workshops", completely and closed all containing action items as well as the topic itself. In the second following meeting we realize that we have to discuss further points concerning this topic (internal workshops). In this case we would like to "reactivate" the very same topic to make sure that the collected informations and decision will be displayed in the topics list of the meeting series together with the informations added previously.

When implementing this feature we should consider that the finalize and un-finalize chain should not get broken.

- [x] A re-opened topic should immediately be copied to the "opentopics" of the series 
- [x] A re-opened topic should immediately be copied to an non-finlalized meeting series (if exists)
- [x] On the MS "Topic" tab only _closed_  topics show a "Re-Open" menu entry below the "three dot" menu icon
- [x] Re-Open first triggers a security question "Do you really want to re-open the already closed topic 'BlaBlaBla'?"
- [x] The source & destination of the re-opend topic gets it `isOpen===true`
- [x] Only moderator can re-open a topic (#Security check in meteor method!!!)
- [x] E2E needed

**Comment by derwok** [comment]
Estimation: 3d

**Comment by derwok** [comment]
Done via PR. Thx!!!  ;-)

Additionally we identified: we have to only copy "pinned info items" (we don't want old, closed action items or old info items to show up in the re-opened topic). Thzis was patched by an additional commit.
