### ISSUE TITLE
If a meeting is un-finalized, it is not possible to delete it - though it has a "blue" trash-icon

### ISSUE THREAD

**Issue by derwok** [4minitz/4minitz#2]
Either remove blue style from trash icon, or make it possible to delete these unfunalized minutes.
![unfinalize-trash](https://cloud.githubusercontent.com/assets/4393698/14943011/b1f853f0-0fce-11e6-8689-52a3fcb63a4c.png)

The 2nd idea sounds complicated... as we have to keep "Open Topics" and "Closed Topics" of the meeting series in sync.

**Comment by derwok** [comment]
After thinking about it: though more complex: I would vote for the second option.
From a user-perspective: After un-finalizing I would expect to be able to delete the complete minutes.

**Comment by felixble** [comment]
Well, then I would suggest to add a new field "isNew" to our topic. With this field it is easy to check if the topic is exclusive for the "to-be-deleted-minute" and will be removed from the open or closed topics of the related meeting series.

Additionally we have to take care about closed topics which were closed within the "to-be-deleted-minute". They can also be identified by the "isNew"-Flag. So all closed-topics of the "to-be-deleted-minute" which are not new will be opened again and added to the open topics of the related meeting series.

**Comment by derwok** [comment]
I tested on port :4000 version. new solution works like a charm!
Thx.!  ;-) I will close this issue.
