### ISSUE TITLE
"Enter"/"Cancel" shall submit/cancel modal dialogs

### ISSUE THREAD

**Issue by derwok** [4minitz/4minitz#20]
Where appropriate ENTER key shall submit modal dialogs like:
- Edit Meeting Series
- Edit Topic
- Edit (Action/Info) Item

ENTER shall not submit on multi-line text areas - here CTRL+ENTER shall submit.

**Comment by migerh** [comment]
What about <select>s, e.g. in the Add Topic dialog? They already react on enter, regardless of ctrl being pressed or not.
