### ISSUE TITLE
Filter "open/closed" topics during minutesedit view with a checkbox "Only open topics"

### ISSUE THREAD

**Issue by derwok** [4minitz/4minitz#201]
As a minutes participant I want to optionally see only open topics of the current meeting minute to quickly spot to-be-discussed topics
- [x] checkbox "Only open topics" behind the ExpandTopics button
- [x] checkbox is initially "de-selected" on opening new minutes
- [x] if checkbox is "true" only open topics are shown in the list
- [x] if checkbox is "true" and a topic is marked "done" - the topic get invisible
- [x] state is realized "per session"
- [x] state is realized with a ReactiveVar

**Comment by woestmannje** [comment]
good idea!
