### ISSUE TITLE
Introduce #Labels for topics

### ISSUE THREAD

**Issue by derwok** [4minitz/4minitz#207]
- [x] "Add Topic" dialog shows input field for labels
- [x] Deletion of labels is possible via dialog
- [x] Labels are persisted to DB
- [x] Database migration exists. Attention! Topics exist at MeetingSeries Level & MinutesLevel
- [x] Labels are inserted into AgendaMails & Protocol Mails
- [x] See InfoItems: it's possible to add an existing or new label by entering "#XXXXX" to the topic description
- [x] Add 2-3 E2E tests

**Comment by derwok** [comment]
Team Estimation: 4 day

**Comment by felixble** [comment]
Good news! For this feature there is no migration needed. Have a look at the [TopicSchema](https://github.com/4minitz/4minitz/blob/develop/imports/collections/topic.schema.js#L13). The topics already have labels-attribute to store an array of label ids ;-) !

All labels available in a meeting series are stored in the meeting series document (attribute "availableLabels"). You can reference them in the topics labels attribute by using the identifiers.
