### ISSUE TITLE
User gets EMail on role change

### ISSUE THREAD

**Issue by derwok** [4minitz/4minitz#211]
If a moderator changes the role for a user send the user an information Mail (see imports/mail/AdminRegisterUserMailHandler.js) - plaintext is OK.

- [x] If roles have changed, ask moderator if she wants to send the Mail or not?
- [x] Consider:
   * Old role => new Role
   * Old Role => None
- [x] Do not send a Mail, 
    * if the role does not change.
    * click on "Cancel"
    * Moderator denied to send notification mails
- [x] Mail should include 
     * a Link to the meeting series
     * Old role / new role
     * Moderator that performed the change

see client/templates/meetingseries/meetingSeriesEdit.js => "submit #frmDlgEditMeetingSeries"

**Comment by RobNeXX** [comment]
Appendix: Only the affected user must be informed

**Comment by derwok** [comment]
Done. Thx!
