### ISSUE TITLE
Performance & Topics Collection - Step 2

### ISSUE THREAD

**Issue by felixble** [4minitz/4minitz#216]
See also the closed previous issue #172.

In the second step of our performance analysis we can use the seeding tool to generate dummy data and analyse our bottlenecks.

Secondly, create a topics collection which avoids the nested structure of the meeting series document. Compare the performance of both scenarios.

# ACs
- [x] Create a new Collection `topics`
- [x] Add `parentId`-Property to reference a topic with its related meeting series
- [x] When finalizing a minutes copy and update its topics and store them in the new collection
- [x] When un-finalizing a minutes perform the necessary topic operations on the new topics collection
- [x] When creating a new minutes query the open topics from the new collection
- [x] When creating a new minutes make sure closed action items and non-sticky info items will not be carried to the new minutes
- [x] On the meeting series items / topics tab query the topics from the new collection
- [x] Feature "re-open topics" should work on the new topics collection
- [x] Collect requirements and make a concept for the order of the topics/items displayed on the meeting series topics/items tab. We will implement this in a separate story: #154 
- [x] Add a db migration which moves all existing topics which are currently stored as subdocuments of the meeting series into the new collection and attach the correct parentId
- [x] Move the subscription of the new topics collection into the template
- [x] Deleting a meeting series should remove its related topics, too
- [x] Purge Topics Collection in end2end helper: e2e.resetMyApp
- [x] Adapt minutes seeding tool

**Comment by felixble** [comment]
Maybe we should first do the migration to astronomy. Relevant issues:

 - [ ] #196

**Comment by migerh** [comment]
> Maybe we should first do the migration to astronomy. Relevant issues:
> 
>  #196

Done.

**Comment by felixble** [comment]
Closed with 80be7c04d3a74a1c5bf7fb2e4181fabdbaadf84d
