### ISSUE TITLE
Improve usability of connection-warning on smartphones

### ISSUE THREAD

**Issue by felixble** [4minitz/4minitz#225]
If the connection is lost a warn icon will be displayed in the upper right corner. On small devices this icon covers the menu icon and makes it impossible to open the navigation menu (see screenshot).

![screenshot_20170423-171753](https://cloud.githubusercontent.com/assets/8507319/25314928/0dd5da98-284d-11e7-85e5-8e6c81a6d2bf.png)

**Comment by felixble** [comment]
Maybe we could use the new "notify flash messages" to display this warning?

**Comment by derwok** [comment]
Seems done.
