### ISSUE TITLE
Edit Item-Dialog does not always work for editing action items

### ISSUE THREAD

**Issue by felixble** [4minitz/4minitz#228]
If you first add an action item, then add a new info item it is not possible to edit the first created action items properties anymore. The dialog opens and all necessary controls are visible but no changes (except the subject) will be saved and the title displays "Edit Information ..." instead "Edit Action Item ...".

**Comment by derwok** [comment]
Actually the app "remembers" the last created Item type (info / action) and and edit of an existing item will always show the edit dialog in the "mode" of the last created item type...
So on edit start we have to specify what type of editor we want. This also plays the role on dialog submit, what fields are saved.
