### ISSUE TITLE
Improve UX on "add first details to Item"

### ISSUE THREAD

**Issue by derwok** [4minitz/4minitz#233]
As a user I want to easily add details to new (Info/Action)Items without beeing surprised.

- [x] Remove the "automatic details editor" trigger after creating new Info/Action Items
- [x] Add Details editor <textarea> to "New Item" dialog below the subject
- [x] This details editor shall allways stay in "Markdown" mode.
- [x] Offer Markdown "?" Help icon that shows markdown help
- [x] Make it possible (with a little triangle) to collapse/expand  the new text area. And remember this state in the user.settings in MongoDB
- [x] If Details are empty - do not add (empty) details

**Comment by iCatCat** [comment]
3d

**Comment by felixble** [comment]
This feature was implemented by PR #261 and covered with an e2e test by PR #279
