### ISSUE TITLE
Improve UX on new InfoItems

### ISSUE THREAD

**Issue by derwok** [4minitz/4minitz#235]
As a user I want to have a default InfoItem subject to speed up my workflow.

Rationale: often we have only one(!) info item for a topic - with added details. In this case users have a hard time to find a good subject for this info item.

- [x] On new InfoItems set a default subject "Info" 
- [x] focus the subject field with "everything is selected"

**Comment by iCatCat** [comment]
1d

**Comment by derwok** [comment]
Done via PR. Thx!  ;-)
