### ISSUE TITLE
Migrate#12 throws exception

### ISSUE THREAD

**Issue by derwok** [4minitz/4minitz#242]
On develop.4minitz.com migrate#12 throws this serverside error:
``` 
I20170508-20:35:44.993(2) (percolate_migrations.js:106) Migrations: Migrating from version 11 -> 12
I20170508-20:35:44.996(2) (percolate_migrations.js:106) Migrations: Running up() on version 12
I20170508-20:35:44.998(2)? % Progress - updating all topics. This might take several minutes...
W20170508-20:35:45.912(2)? (STDERR) /home/4min/.meteor/packages/meteor-tool/.1.4.4_1.1i2oifc++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:280
W20170508-20:35:45.912(2)? (STDERR)                                           throw(ex);
W20170508-20:35:45.913(2)? (STDERR)                                           ^
W20170508-20:35:45.913(2)? (STDERR) 
W20170508-20:35:45.913(2)? (STDERR) TypeError: Cannot read property 'forEach' of undefined
W20170508-20:35:45.914(2)? (STDERR)     at MigrateSeriesUp._updateInfoItem (server/migrations/migrate_v12.js:101:9)
W20170508-20:35:45.914(2)? (STDERR)     at server/migrations/migrate_v12.js:95:18
W20170508-20:35:45.915(2)? (STDERR)     at Array.forEach (native)
W20170508-20:35:45.915(2)? (STDERR)     at MigrateSeriesUp._updateTopic (server/migrations/migrate_v12.js:94:25)
W20170508-20:35:45.916(2)? (STDERR)     at server/migrations/migrate_v12.js:88:18
W20170508-20:35:45.917(2)? (STDERR)     at Array.forEach (native)
W20170508-20:35:45.917(2)? (STDERR)     at MigrateSeriesUp._updateTopicsOfMinutes (server/migrations/migrate_v12.js:87:24)
W20170508-20:35:45.917(2)? (STDERR)     at MigrateSeriesUp.run (server/migrations/migrate_v12.js:45:28)
``` 
As it turns out: Infoitems.details is an **optional** attriibute. There exists InfoItems without any details (even not an emopty array).
So all usages of InfoItem.details must be protected against an undefined details attribute.

In migrate_12.js there are at least 6 usages of `xxx.details` that must be protected.

**Comment by migerh** [comment]
Some hints.

Protecting the usage is usually done with an `if`-Clause:

    if (infoItems.details) {
        …
    }

Instead of copy-pasting that all over the file, consider using a helper function that checks this:

    function forEachDetail(infoItems, operation) {
        if (infoItems.details) {
            infoItems.details.forEach(operation);
        }
    }
    …
    forEachDetail(infoItem, detail =>{
        delete detail._id;
        delete detail.createdInMinute;
    });

For the code that runs `xxx.details.forEach` not much changes but we still get the benefit from checking if the `details` property exists.
