### ISSUE TITLE
Security aspects for E-Mail Validation

### ISSUE THREAD

**Issue by felixble** [4minitz/4minitz#250]
As an admin I want to be sure that people without a validated email address are not allowed to view or manipulate any data.

# ACs
- [ ] The route to a minutes or a meeting series should not be visible for not-verified users
- [ ] Meeting concerned emails (agenda, info- / action-items) should not be sent to not-verified users
- [ ] A not-verified user should not be able to view / manipulate series or minutes even if he calls the meteor methods directly

## Further aspects

As a admin I would like that all emails send by the system will be send via the same delivery method set in the 4minitz settings. Currently the mails send by the account system (e.g. email to validate the email address) are sent via smtp directly.

**Comment by derwok** [comment]
We changed the behaviour: A non-verified user simply can not log in.
see imports/config/accounts.js
