### ISSUE TITLE
Details text field does not keep line break when out of focus. Is this wanted behaviour?

### ISSUE THREAD

**Issue by librue** [4minitz/4minitz#26]

**Comment by derwok** [comment]
Felix added Markdown support to this field - for simple richtext-formatting.
Markdown needs one extra&empty line to insert a line break.
Maybe we should clarify somewhere - at least in the docs. Or with placeholder-hint?

**Comment by librue** [comment]
Ah, I see :) I will check how the placeholder-hint looks like.

**Comment by derwok** [comment]
Added placeholder with commit cc22515ba0ae7a4f495371721cf4c97aebff5eec
