### ISSUE TITLE
HTML Document generation (2)

### ISSUE THREAD

**Issue by derwok** [4minitz/4minitz#267]
Compare to issue #39 - all applicable ACs from there apply here - but in this first user story we want to generate HTML docs.

```
    "DocGeneration": {
        "enabled": true,
        "format": "html"
        "targetDocpath": /4minitz_data/files/protocols"
    }
``` 
Use the HTML mails that are going to be send as meeting minutes...

Make a modular architecture that lateron allows to add "PDF" format.

**Comment by woestmannje** [comment]
Team estimation: 3-4d

**Comment by derwok** [comment]
Thx. ;-)
