### ISSUE TITLE
InfoItem Editor opens for wrong item

### ISSUE THREAD

**Issue by felixble** [4minitz/4minitz#271]
Steps to reproduce:

1) Add two info items to a random topic
2) open editor for one of both info items and close it again
3) add a third info item
4) BUG: Click on the 2nd info item -> the first one will be edited!

**Comment by derwok** [comment]
May have the same root cause... but in the above scenario the "Add Details" trigger also opens details on the wrong item.

**Comment by felixble** [comment]
@derwok strange, I cannot reproduce the issue concerning the "Add Details" trigger. Editing the info items seems to work sometimes, too. I added a topic with six items. It worked for all except the second one...?!

We use the jquery api to read the `data-index` attribute to locate the correct info item. This returns the wrong index (sometimes...). So I switched to the `getAttribute`-method of the plain javascript DOM-Element. This worked for me. I will merge the changes. @derwok Could you please test the results in your environment, too?

**Comment by derwok** [comment]
I thoroughly checked this fix on our /develop/ branch. I could not reproduce the problem. Neihter by clicking on the Item Subject, nor by clicking on "Add Details..." - it all worked as expected!
Thankx for the fix!  ;-)
