### ISSUE TITLE
Current /develop/ branch breaks loading in IE11

### ISSUE THREAD

**Issue by derwok** [4minitz/4minitz#282]
Simply loading https://develop.4minitz.com/ with InternetExplorer11 gives an empty Screen. And this error in the console:

    SCRIPT1002: Syntaxfehler
    Datei: 9f036544bb2342454982fdf31886e6876a6fab53.js, Zeile: 13, Spalte: 248856

See screenshot for syntax error Location. Seems to be somewhere at imports of dependencies of fs-extra...

![4minitzinternet explorer_2017-07-03_11-05-45](https://user-images.githubusercontent.com/4393698/27786089-0c3e4a1a-5fe0-11e7-89e4-82669858bf47.png)

@migerh: could you have a look?!

**Comment by migerh** [comment]
Apparently meteor does not transpile node_modules or meteor packages:

https://forums.meteor.com/t/npm-modules-using-strict-mode-not-working-in-meteor-1-3/19790/5

So the only clean way to fix this is to remove fs-extra from client code entirely and make sure that all code that uses it is only loaded on the server.
