### ISSUE TITLE
2 column participant layout broken on Chrome

### ISSUE THREAD

**Issue by derwok** [4minitz/4minitz#289]
Minutes Edit => Participants 2 column: layout broken on Chrome if first participant of 2nd column marked

@Students: timeboxed: 4hrs

**Comment by derwok** [comment]
Before:
![image](https://user-images.githubusercontent.com/4393698/28331642-1d5a47ea-6bf2-11e7-965e-61c2a1e19899.png)

After:
![image](https://user-images.githubusercontent.com/4393698/28331658-311d2cd4-6bf2-11e7-835a-8840acf7374f.png)

**Comment by RobNeXX** [comment]
Fixed
I installed an older version of Chrome and the lastest version of Chrome and it worked on both.
It's just a bug in some Chrome versions

**Comment by derwok** [comment]
Yes, you are right.
With Chrome 59.x on Mac the problem was there, so I just now upgraded to Chrome 60.x.
Now: problem is gone! - so we don't take further actions here.
Thanks for investigating. => Close
