### ISSUE TITLE
Searchbar for list of meeting series

### ISSUE THREAD

**Issue by derwok** [4minitz/4minitz#299]
As a power user I want to filter the list of visible meeting series to have quick access to a desired series

- [x] Show searchbar behind "New Series" button
- [x] Show searchbar only if >4 meeting series are visible for user
- [x] Filter list of meeting series while user types 
- [x] Filter should search for substring inside project_name & meeting_name
- [x] Optional: split search term on whitespace, combine search phrases by "$AND"

**Comment by derwok** [comment]
Lukas will take care

**Comment by felixble** [comment]
Maybe our [QueryParser](https://github.com/4minitz/4minitz/blob/develop/imports/search/QueryParser.js) can be used to split the search term into tokens. This allows the usage of additional keywords e.g. `do:match-case` to enable case sensitive search.

It might be necessary to expand this parser by an options argument to turn of the label-parsing feature which is not desired when parsing the search query for the meeting series filter.
