### ISSUE TITLE
The finalized-by username is only visible for the user who finalized the minute himself

### ISSUE THREAD

**Issue by felixble** [4minitz/4minitz#3]
<img width="322" alt="bildschirmfoto 2016-05-02 um 15 34 25" src="https://cloud.githubusercontent.com/assets/8507319/14955603/64931de0-107b-11e6-922e-fdb32716c481.png">

Cause: We have not special publication for the users collection, so only the row of the current user is visible. Which means the client cannot query for a username with a different userid.

Solution: We could either store the username who finalized the minute (instead of his id) or we could provide a meteor method which returns the username to a given userid.

**Comment by felixble** [comment]
To fix this bug I will store the username of the user who finalized the minute (instead of his id) at the moment. Later we can think about this problem again after we have added a role concept.

**Comment by derwok** [comment]
Checked with current release-prep version.
With current version users can not change their login-names anyway.
;-)
Thx! Will close this issue.
