### ISSUE TITLE
Very minor Bug by user changing own mail address to an already existing one with e-mail verfication enabled

### ISSUE THREAD

**Issue by ampasc** [4minitz/4minitz#321]
This bug will occur when a user tries to change his/her mail adress to a already existing one via the profile edit dialog if the e-mail verfiication feature is enabled at the same time.

By trying to change the mail adress in the above described way the system will first inform the user about the need an an re-verification after changing the mail:

![grafik](https://user-images.githubusercontent.com/26335195/30282673-41b64a9a-9716-11e7-8fba-3c1562cb59f6.png)

It will then show the error due too the mail adress being already taken:

![grafik](https://user-images.githubusercontent.com/26335195/30282705-57cb55b4-9716-11e7-836c-0225b48f6db1.png)

Since the occurence of this error the user data is not changed in any ways.

Afterwards the edit profile dialog will remain open but pressing the change button won't do anything. The dialog may then be exited by using the cancel button.

Since this bug doesn't lead to wrong data and it having an assumable near-to-zero probability of occuring in a real production system (due to all the necessary circumstances that have to get together) it has to be decided whether it should be fixed at all.

**Comment by derwok** [comment]
While I agree that the re-verification message box should be ommited in this case...

**I will close** this issue, as 
* the system behaves stable 
* Nothing wrong is stored to DB
* user is informed about the problem, so user can fix by entering other EMail
* probability to run into this case is very low
* "Re-verify" message is generated in the front end, while the "duplicate mail" exception is generated in the backend => fixing would be really complicated

Nevertheless: Thanks for reporting!
