### ISSUE TITLE
Visual Clue for "topics that will show up in next meeting"

### ISSUE THREAD

**Issue by derwok** [4minitz/4minitz#323]
As a user I want to have a clear visual hint if a topic shows up in the next meeting.
* If topic will not show up:
   ~~* Make topic 70% opaque~~ too many edge cases (see below) complicated
   * Add label "Completed" (style like "New")
* ~~For printing: make completed topics 100% opaque temporary~~
* ~~On MS topic history all topics are 100% opaque~~
* ~~On EMails & HTML protocoll download all topics are 100% opaque~~
* The "completed" visualization is visible in the minutes view even after finalize
* "Completed" visualization is visible for all user roles
* "Completed" visualization is realtime reactive. (e.g., toggle embedded AI as done, set topic to recurring, mark topic as discussed => re-calculate completed state).
* Give "Completed" label a tooltip "This topic is completed and won't show up in the next meeting"

Hint:
Use `topic.isClosedAndHasNoOpenAIs()`for this check and rename the method to `topic.isFinallyCompleted()`

**Comment by felixble** [comment]
As @migerh suggested we could work with opacity. Take a look at the following screenshot.
![bildschirmfoto 2017-10-07 um 18 46 00](https://user-images.githubusercontent.com/8507319/31309982-fa4b15f8-ab8f-11e7-9c0e-fbc0b222989b.png)

**Comment by derwok** [comment]
I will ommit the opacity idea (though it is quite cool!) - but it will bring too many edge cases.
Like: we don't want opacity on
* printing
* send EMail minutes
* topic history
* ... (where else?)

So, I'll just add a label with a tooltip.
![grafik](https://user-images.githubusercontent.com/4393698/41336402-6d66ee7a-6eec-11e8-8167-d35ec9857b90.png)
