### ISSUE TITLE
 [v1.x] MyActionItems

### ISSUE THREAD

**Issue by derwok** [4minitz/4minitz#33]
- [ ] A new Tab is introduced on the 4Minitz main page: "ActionItems". 
        The old content goes to Tab "Meetings"
- [ ] I See Action Items of all Meetings where I am invited & where I am responsible for the AI. (Compare Item-List on each Meeting Series)
- [ ] Sort order should be "due date"
- [ ] I can filter for open and closed AIs - default is: show only open AIs
- [ ] AI display is "read only" (e.g. it's not possible to check AI as done).
- [ ] Optional: bring in the filter possibilities of the "Items" tab a meeting series

Hints:
* recycle as much of the existing display logic of the existing "Item" tab of a specific meeting series. Do not re-invent the wheel. 
* The content of action items list does not need to be "reactive". Releoad to refresh is O.K.

**Comment by felixble** [comment]
If the issue #281 is already implemented the use should be able to switch between: sort by "due date" and sort by priority.

**Comment by woestmannje** [comment]
Team estimation: 4d

**Comment by derwok** [comment]
Done
