### ISSUE TITLE
"New" label is incorrectly invalidated

### ISSUE THREAD

**Issue by symonra** [4minitz/4minitz#334]
It seems as if under certain circumstances an infoItem is not invalidated properly and its "New"-label will be displayed in the topic history of the meeting series. 

**Expected Behavior:**  
I would expect the "New"-label to show, only if the infoitem was added in the last minute. But that is not the case. 

**Steps to reproduce:**
1. Add new minute
2. Add Topic with an infoitem
3. Finalize minute
4. Add new minute 
5. Add another infoitem to the same topic
6. Finalize minute

Now you can add and finalize as many minutes as you like without the "New"-label ever disappearing in the history.

Additional info: I havent found a way for the infoitems to get invalidated correctly after the incident. Moreover every infoItem that is added to the topic will show the same behavior and keep its "New"-label in the history.

**Comment by felixble** [comment]
I think, Ich found the root cause of this bug: In line https://github.com/4minitz/4minitz/blob/4622a76aa1c7d6229b88db68a3b05293d6edb074/imports/services/finalize-minutes/meetingSeriesTopicsUpdater.js#L12 we should use the Method `TopicsFinder.allTopicsOfMeetingSeries` instead.
