### ISSUE TITLE
Performance of typeahead/select2 with thousands of users

### ISSUE THREAD

**Issue by derwok** [4minitz/4minitz#343]
As an enterprise user I want to work with arbitrary colleagues from my company whithout performance / memory issues. (e.g., US DoD has 3.2 million employees) ;-)

1. Make performance test with 1000; 5000; 10,000, 50,000 users. How behaves memory / performance? Still "realtime"?
1. If we have problems with 10,000 users in DB, then change typeahead & select2 to use lazy loading after at least 3 letters entered

* Typeahead: Used on Meeting Series Editor for Invited/Informed
   http://twitter.github.io/typeahead.js/examples/
* Select2: Used on Responsibles for Topics / ActionItems
   https://select2.org/

**Comment by ampasc** [comment]
Team estimation for effort: 4 days
