### ISSUE TITLE
Evaluate the SVG framework of FontAwesome Pro 5

### ISSUE THREAD

**Issue by derwok** [4minitz/4minitz#344]
As a user with blocked "font loading" I want to see 4Minitz Icons so that I can use the App

Ask WOK for "Installer".

* Does it work with IE11?
* Generate a table with all glyphicons and proposals for new FontAwesome Icons
* Replace <glyphicons> in our app with FA5-Pro icons.

Opentopic: currently only the "Pro" version is available and clarification is ongoing if we can either use this in our MIT project or if SVG framework is included also in FA5Free

**Comment by ampasc** [comment]
Team estimation for effort: 3 days

**Comment by derwok** [comment]
Thanxs for the mapping table.
We'll wait for FA Pro 5 Release and check if license is applicable for 4Minitz.
