### ISSUE TITLE
Add more quality checks on Finalize / Send Agenda

### ISSUE THREAD

**Issue by derwok** [4minitz/4minitz#345]
As a moderator of a meeting minutes I want to have quality checks on Agenda/Finalize so that I dont make "known" mistakes.

* Make architecture for "Finalize Check" more generic.
* Allow checks on "Send Agenda" / "Finalize" / "...-future feature..."
* Allow to add more checks easy
* Architecture shall allow to switch on/off checks
* Architecture shall allow to generate list of all checks...

* Implement checks before (F)inalize & (A)genda Mails
  * No participant marked present (F)
  * No topic in minute (F) (A)
  * No topic checked (F)
  * Topic checked, but no children (F)
  * Action Item with NO responsible (F)
  * Optional: Topic checked, but no "updated or new" content (F)

**Comment by ampasc** [comment]
Team estimation for effort: 3 days

**Comment by derwok** [comment]
Great! Works!
Thx!  ;-)
