### ISSUE TITLE
Export/import of meeting series from server to a different server

### ISSUE THREAD

**Issue by derwok** [4minitz/4minitz#365]
- [ ] This is admin only!
- [ ] Make it a server side commandline tool (exporting attachments via browser UI seems too complicated right now)
- [ ] Keep MS / Minute / Topic IDs
- [ ] But allow adaption of user IDs - because users may have different IDs between two servers

**Comment by knoidc** [comment]
Hi. @derwok is the usage of this function documented somewhere? How can I call this function?
