### ISSUE TITLE
Spelling Mistake - "Open Minute"

### ISSUE THREAD

**Issue by andyshilton** [4minitz/4minitz#369]
When receiving agendas from the system, links are added at the bottom of the page for "Open Series" and "Open Minute". Should the latter not say "Open Minutes"?? Simple bug, but thought it worth pointing out anyway :)

![image](https://user-images.githubusercontent.com/16556349/32493229-ffcc8aec-c3b4-11e7-9aad-57548740d10e.png)

**Comment by felixble** [comment]
Thank you for letting us know. I fixed it in our develop branch. It'll be shipped in our next release.

**Comment by andyshilton** [comment]
Thanks :) Brand new to 4minitz, but loving it already so thank you for the hard work :)

**Comment by felixble** [comment]
@andyshilton Thanks for your feedback. We are happy to hear that ;-). If you have any trouble or questions feel free to ask us.
