### ISSUE TITLE
Ability to convert an info item to an action item.

### ISSUE THREAD

**Issue by terryb8s** [4minitz/4minitz#377]
We have tested 4minitz out for a weekly meeting we have and I have to say it was pretty great even with only one of us moderating,

The thing I kept doing was creating an info item that then ended up morphing into an action item by the end of the topic, can we please have a way to convert an info item to an action item?

I had a good look around to see if this is in the works but could not see anything, so I apologize if I am doubling up.

Cheers

**Comment by felixble** [comment]
Yes, this happened to me, too, sometimes. Converting info items to actions (and vice versa) seems to be a simple job - at the first sight. But, when an item will be carried to the following meetings (e.g. an action item or a pinned info item) things get complicated.

However, I think the common scenario is that you realize quite after creating a new info info that you actually needed an action item instead (or the other way around).

So I would suggest to simplify this feature by adding the following constraint: A new item can only be converted between both types if it was created in the current minutes. An item created in a previous minutes cannot be converted anymore.

@terryb8s do you agree with this solution?

**Comment by terryb8s** [comment]
Yes I can see why it would get complicated when carried over to a new meeting.

Yes I agree with your solution but would probably want the convert button (if that's how your going to implement it) to stay present but greyed out for the item when carried over to a new meeting, and maybe have a tooltip stating why its greyed out. This way users wont get confused and wonder why they are unable to convert.

The tooltip could have something like this "Conversion disabled: item exists in past meeting <Meeting Name>"

I hope this makes sense.

**Comment by felixble** [comment]
This definitely make sense ;-). We have a similar concept for deleting topics which is also only allowed in the minutes in which the topic was created. In further minutes we display a small dialog with the explanation (and eventually present a "close-this-topic-and-all-included-actions" button). Maybe a tooltip would be less intrusive.

I will take up this feature request into our backlog ;-)
