### ISSUE TITLE
User admin page limited to 250 users

### ISSUE THREAD

**Issue by terryb8s** [4minitz/4minitz#378]
Hi,

It appears that currently the user management page is limited to 250 users being shown, we have been testing with about 450 users so need a next page button or something similar.

Cheers

**Comment by derwok** [comment]
Hi,
Thanks for your comment.

Yes the 250 limit is intentionally. We did not want to slow down the Ui with potentially thousands of users.

The admin users view is mainly to find users (thus the filter possibility), then to activate/deactivate a standard user and to write an email to a user, even the user id retrieval is interesting (works also via filter). So, all this is grouped around the filtering feature.

It was never intended to "paginate" through all users.
But I see improvement potential here to inform the admin that only XXX of YYY users are displayed.

Could you tell us a possible use case why you would paginate through all(!) users?

**Comment by derwok** [comment]
Just added a statistics hint to the end of the user list:
![grafik](https://user-images.githubusercontent.com/4393698/33525982-b7c6a054-d839-11e7-822c-f6326b768f79.png)

**Comment by terryb8s** [comment]
Yeah I think that's good a good solution, what I was trying to do was disable a bunch of service accounts that got added by the LDAP import but that's my fault for not filtering them.

The scenario I can see that might be similar to that is if you had a group of people who left e.g. a class of students, means you can scroll through without typing names, but you are probably right filtering is probably quicker.

**Comment by derwok** [comment]
New Statistics and existing filter feature solve issue. Will close.
