### ISSUE TITLE
Reoccurring global note?

### ISSUE THREAD

**Issue by terryb8s** [4minitz/4minitz#382]
We are using the global note to outline the purpose of the meeting and some housekeeping, Can this be made reoccurring?

I imagine if iCal support is added this would be sent within an iCal as the body?

P.S. Please tell me if I am over stepping or should be adding feature requests elsewhere.

**Comment by derwok** [comment]
Idea: provide "sticky" pin behind global note to propagate note to next meeting.

**Comment by derwok** [comment]
Hey Terry. 
We could manage to implement this idea on current /develop/ branch.
We are planning to publish a new release in the next few days on /master/ branch.
Stay tuned.
