### ISSUE TITLE
`importCronTab` and `importOnLaunch` incompatible?

### ISSUE THREAD

**Issue by migerh** [4minitz/4minitz#384]
According to #348 the two settings are not compatible. I can't see why this should be the case so we should check this.

**Comment by terryb8s** [comment]
Ok after a bit more testing with this it does work (egg on my face sorry) had the settings like this "importCronTab": "* 59 * * * *" and nothing was happening but "importCronTab": "*/59 * * * *" seems to work.

Can close this.

**Comment by migerh** [comment]
Ah, I see. Thanks for the update.
