### ISSUE TITLE
Multiple LDAP searchFilters

### ISSUE THREAD

**Issue by migerh** [4minitz/4minitz#385]
According to #348 it is not possible to have multiple searchFilters. We should check if we have an issue in our code or if we don't we should enhance the documentation, maybe add a link to some LDAP docs that describe the searchFilter in more detail.

**Comment by derwok** [comment]
According to @terryb8s in #348:
> Also it appears I can't add more than one searchfilter otherwise it complains about to incorrect use of parentheses, maybe I just don't understand the syntax for this?

Here is a "multi searchfilter" from a working configuration of mine:
```
"searchFilter": "(&(department=SW*)(objectClass=user))",
```
@terryb8ts: Please state if you searched for something like this?
Does this work for you?

**Comment by terryb8s** [comment]
Ok sorry as I said I think I was getting the incorrect syntax

(&(objectCategory=person)(!(mail=change.me@workplace.org))(mail=*)(objectClass=user))

This works now, was missing the &.

I think you can safely close this one, will #348 be merged at some point?

**Comment by derwok** [comment]
Thanx for your comment. 
Will close this one. 
Yes #348 will be handled. I think in year switch 2017/2018 should be some time.
