### ISSUE TITLE
User action items don't show parent topic.

### ISSUE THREAD

**Issue by terryb8s** [4minitz/4minitz#387]
Hi I am just reviewing the action items I had from a previous meeting and noticed that some of the action items are named something like "Terry to upgrade" but without the topic I don't know what I am upgrading, I know there is the ability to have details but it would be easier to just show the topic that the action item was in.

Can we please have the parent topic added to action item in some way? this is in the action items tab.

**Comment by derwok** [comment]
Hi Terry,
sorry for not commenting so long on this issue. Yes, you're right this would be a great improvement. We actually plotted out this idea already here: #313 
(And actually this issue is on our short list!)

So, we will close this topic here as duplicate.
