### ISSUE TITLE
 [v1.x] PDF Export / E-Mail of Meeting Minutes

### ISSUE THREAD

**Issue by derwok** [4minitz/4minitz#39]
As a moderator I want to have PDF/A versions of my meeting protocols for long time archiving.

- [x] Look at these command line packages:
https://wkhtmltopdf.org/
http://stackoverflow.com/questions/1659147/how-to-use-ghostscript-to-convert-pdf-to-pdf-a-or-pdf-x
- [x] Allow to switch on/off PDF generation and pathes to the above package binaries settings.json

```
    "DocGeneration": {
        "enabled": true,
        "format": "pdf"
        "pathToWkhtmltopdf": "/usr/local/bin/wkhtmltopdf",
        "pathToGhostscript": "/usr/local/bin/gs",
        "targetDocpath": /4minitz_data/files/protocols"
    }
``` 

- [x] Make a "launch" test: 
     - If feature is enabled via settings but one of the necessary binaries is missing, generate an error message with hint what is missing
     - Check targetPDFpath if it exists, if not create it, check if write permissions exist, if not report error.
- [x] On finalizing of minutes generate a 1:1 PDF/A version of the HTML protocol that is already send via EMail
- [x] If PDF/A generation goes wrong (e.g. needed binary is missing), log error to server log and show error as "Toast" to moderator.
- [x] Allow to download the PDF/A from the minutes view via the same mechanism as the binary attachments. But with a separate file collection. (PDFs should *not* count as attachments!). 
- [x] Below the "targetDocpath" create a sub dir with the meetingSeries ID "abcDe1234deFG", below this create a sub dir per year (e.g. "2017") and put PDF there (MeteorFiles module will specify the filename). On download the name should be: "MeetingSeries-Name - YYYY-MM-DD.pdf"
- [x] On meeting un-finalize: delete the existing PDF minutes. Only one (the last!) protocol of finalized minutes shall be stored in the file system.
- [x] Only "Invited" (not informed!) users should have access to the PDF protocol, even if the have a proper download URL (compare to file attachments).
- [x] Adapt the admin doc and describe the steps necessary to generate PDF/A
- [x] Cover functionality with E2E test (we should be sure it works, if helper binaries are at place)

**Comment by ampasc** [comment]
Team estimation for effort: 3 days

**Comment by derwok** [comment]
Works great!
Will close issue.
Thx!
