### ISSUE TITLE
Docker version ldap error

### ISSUE THREAD

**Issue by no7ren** [4minitz/4minitz#392]
I have installed one docker version and changed the 4minitz_settings.json as proposed in the documentation. And I always get the following error:
{"dn":"","code":49,"name":"InvalidCredentialsError","message":"80090308: LdapErr: DSID-0C090400, comment: AcceptSecurityContext error, data 52e, v1db1\u0000"}
LDAP bind failed with error

I have tested it with my own ldapsearch function and it went well.

**Comment by derwok** [comment]
Hi,
Great you try 4Minitz.  ;-)
The error you describe is common to LDAP servers that do not allow anonymous access to their DB.
If you get this error message, you must authenticate with your LDAP server.
Extra for this case 4Minitz has - inside the LDAP section - the auth setting described here:
https://github.com/4minitz/4minitz/blob/develop/doc/admin/adminguide.md#authentication


Please set as described - in my case I could uses something like this:
```
"ldap": {
        "enabled": true,
        "authentication": {
                "userDn": "DOMAINCTL\\username",
                "password": "p@ssw0rd"
        }
       // ....
}
``` 
Please report back if this helps you.

**Comment by no7ren** [comment]
Thank you for the quick response. I do put the user name and password like what you said but still it gave me the error. I tried both with only the username "testuser" or the full DistinguishedName "CN=testuser,OU=test Services and Applications,DC=test,DC=company,DC=net". The first one throw me the above error while the second try throws me one more error "SizeLimitExceededError: Size Limit Exceeded". I tried to run the getLDAPUser.js with only the username "testuser" as userDn and it successfully binded (I tried with node version 7.10.1). 
I hope you can light some shed on it.

**Comment by no7ren** [comment]
I figured it out myself. 
In my case, I have to set the "username": "uid"

Now it works!
