### ISSUE TITLE
Support Redis as alternative to MongoDB?

### ISSUE THREAD

**Issue by poVoq** [4minitz/4minitz#396]
For various reasons people might not want yet another database system on their server (not getting into discussions about MongoDB in general). Redis seems like a popular & performant option that is quite commonly used as an alternative to MongoDB.

Any plans for supporting Redis? Thanks!

**Comment by derwok** [comment]
Hi, Thanks for your feedback!
We will not change DB backend at this stage of the project.

Two major reasons: 
1. The JS framework Meteor that we use is tightly coupled with MongoDB. Main reason here is: it uses the DB insert/update/delete events (OpLog) to trigger client frontend changes for all connected clients. This enables realtime updates accross all connected clients.
1. Our docker deployment bundles a perfectly matching MongoDB inside the docker image. So, setup with docker is a no-brainer and after removal of docker container/image no traces left of MongoDB on your system.
