### ISSUE TITLE
Enhancement Idea: Timed topics.

### ISSUE THREAD

**Issue by terryb8s** [4minitz/4minitz#405]
One of the staff here mentioned that it would be good if during a meeting that topics could optionally have a topic length added to them which is timed with a visual countdown and sounded warning for at say 70% and 100% (Maybe these thresholds can be set?), this can be used to keep people on topic, we find that a lot of meetings run into over time because people go off topic and spend too long talking about something that can be discussed outside of the meeting.

**Comment by derwok** [comment]
This seems like a good idea. 
We actually have a similar issue here: #51 *Start/Stop Time for Meetings / Topics* - let's continue dicussion over there.
