### ISSUE TITLE
LDAP importCronTab creates "TypeError: db.collection is not a function" errors in serverside log

### ISSUE THREAD

**Issue by derwok** [4minitz/4minitz#406]
We use the current /develop/ branch as of this writing.
I have this line in my settings.json `ldap`section: ` "importCronTab": "* 22 3 * * *"`

Every night at exactly 3:22 I see this in my log file:
``` 
20180117-03:22:00.575(1) (STDERR) An error occurred: TypeError: db.collection is not a function
20180117-03:22:01.441(1) (STDERR) An error occurred: TypeError: db.collection is not a function
20180117-03:22:02.430(1) (STDERR) An error occurred: TypeError: db.collection is not a function
20180117-03:22:03.434(1) (STDERR) An error occurred: TypeError: db.collection is not a function
20180117-03:22:04.430(1) (STDERR) An error occurred: TypeError: db.collection is not a function
20180117-03:22:05.434(1) (STDERR) An error occurred: TypeError: db.collection is not a function
20180117-03:22:06.432(1) (STDERR) An error occurred: TypeError: db.collection is not a function
20180117-03:22:07.432(1) (STDERR) An error occurred: TypeError: db.collection is not a function
20180117-03:22:08.427(1) (STDERR) An error occurred: TypeError: db.collection is not a function
20180117-03:22:09.434(1) (STDERR) An error occurred: TypeError: db.collection is not a function
20180117-03:22:10.431(1) (STDERR) An error occurred: TypeError: db.collection is not a function
20180117-03:22:11.428(1) (STDERR) An error occurred: TypeError: db.collection is not a function
20180117-03:22:12.453(1) (STDERR) An error occurred: TypeError: db.collection is not a function
```  

Every second one of these lines. For exactly one minute. ~ 60 error entries in log.

This seems like a mongodb related issue: https://www.google.de/search?q="TypeError%3A+db.collection+is+not+a+function"
 
We use meteor 1.6.0.1 with the embedded mongodb v3.2.15:
``` 
#  meteor mongo
meteor:PRIMARY> db.version()
3.2.15
``` 
These mongo related npm packages are installed:
```
├── mongo-uri@0.1.2
├─┬ mongodb@3.0.1
│ └─┬ mongodb-core@3.0.1
│   ├── bson@1.0.4 deduped
│   └─┬ require_optional@1.0.1
│     ├── resolve-from@2.0.0
│     └── semver@5.4.1 deduped
├─┬ mongodb-extended-json@1.10.0
``` 

Any idea?

**Comment by migerh** [comment]
Mongo db driver had a breaking api change in 3.0:

https://github.com/mongodb/node-mongodb-native/blob/3.0.0/CHANGES_3.0.0.md

connect now returns a client object instead of a db object.

**Comment by derwok** [comment]
I did a `git cherry-pick 75faa11a834eda8df151ed1fd547cee036842cfa` on your fix on a "semi-production server". Then manually imported users `node ./private/ldap/importUsers.js ...` - and it worked like a charm.

One concern: so, we have now a breaking change regarding older MongoDB <3.0 systems?
Is this an issue? Do we have to somewhere state in the docs, that if admin brings his/her own MongoDB server, it must be a version >= 3.0? Is this right?

**Comment by migerh** [comment]
No. The MongoDB server was not updated. But the nodejs mongodb driver was updated to 3.0.0:

https://github.com/4minitz/4minitz/commit/65a76147d11ae1558e8239cd0f2988cf5dd2cca1#diff-b9cfc7f2cdf78a7f4b91a753d10865a2

Since that is configured in our `package.json` we're safe.

**Comment by migerh** [comment]
PR #412
