### ISSUE TITLE
Labels for AI/Info Items

### ISSUE THREAD

**Issue by derwok** [4minitz/4minitz#42]
As a moderator I can add labels to Action & Information Items to easily find/sort/group my items by type

- [x] Research http://bootstrap-tagsinput.github.io/bootstrap-tagsinput/examples/
- [x] Reasearch also "Select2" which seems more mighty...  https://select2.github.io/examples.html and has a recently updated atmosphere package: https://atmospherejs.com/natestrauser/select2
- [x] Globalsettings provides default labels: 
Status:RED, Status:YELLOW,Status:GREEN (with according colors)
Decision, Milestone, Escalation, Audit-Finding, "Decision Proposal" with other default colors
- [x] settings_sample.json has labels with colors (see above)
- [x] If a pattern /(^|[\s.,;])#([^\s.,;]+)/ is detected in the subject field - after SAVE - , this label is added to the item
- [x] creating a new meeting series copies all default labels from the settings to a list of known labels within this series
- [x] If a new label is detected by regExp it is added to the list of known labels of meeting list & the item
- [x] render labels as bootstrap-tags or badges with color & text
- [x] Labels should be configurable for each meeting series seperately
- [x] It must be possible to rename labels of a meeting series. This will rename the label for all minutes/items of this meeting series.  - needs no reactivity here!
- [x] Changing the default labels provided by the settings.json must NOT change the labels of all topics/items of all meeting series
- [x] Delete of a label from a meeting series deletes this label from all child minutes - finalized & un-finalized!
- [x] Labels must be part of sent E-Mails

**Comment by felixble** [comment]
Set text color based on background: http://stackoverflow.com/questions/11867545/change-text-color-based-on-brightness-of-the-covered-background-area

**Comment by derwok** [comment]
I (&Michael G.) see one problem here:
Giving a color name like "pink" - e.g. in a subject text: #mytag#pink or in the label editor crashes the whole label editor afterwards. As the code tries to parse #xxxxxx RGB code from "pink".

**Comment by derwok** [comment]
Take a look at these bootstrap colorpickers. Would be nice to integrate one into the "Meeting Series Editor for Labels":

http://lauren.github.io/pick-a-color/ (MIT License)
   or
https://mjolnic.com/bootstrap-colorpicker/ (Apache License)
