### ISSUE TITLE
Demo hint on resend verification email page

### ISSUE THREAD

**Issue by migerh** [4minitz/4minitz#423]
The demo user hint box is visible on the verification email resend page. The information is irrelevant on that page and should be removed.

![image](https://user-images.githubusercontent.com/368715/37518455-7cc146b2-2915-11e8-97b3-6ce00f4f2b70.png)

**Comment by derwok** [comment]
See: https://github.com/meteor-useraccounts/core/blob/master/Guide.md
I think the reactive `AccountsTemplates.getState() === 'signIn'` will help here.
Let me give it a shot!
