### ISSUE TITLE
TLS support?

### ISSUE THREAD

**Issue by migerh** [4minitz/4minitz#43]
If we want to use 4minitz.com productively for 4minitz meetings we should look into encrypting connections to our server via TLS.

Maybe use Let's Encrypt?

**Comment by derwok** [comment]
- [ ] add a Let's Encrypt certificate to the server 4minitz.com
- [ ] close all ports except 80, 443, 4000 (develop-branch)
- [ ] redirect port 80 => port 443 => port 3000 (master-branch)
- [ ] put "letsencrypt-auto renew" to weekly crontab
Test with:
* http://4minitz.com  => master with SSL
* http://www.4minitz.com  => master with SSL
* https://4minitz.com   => master with SSL
* https://www.4minitz.com   => master with SSL
* http://4minitz.com:4000     => develop NO SSL
* http://www.4minitz.com:4000   => develop NO SSL
