### ISSUE TITLE
ADD TOPIC (to end of list)

### ISSUE THREAD

**Issue by AtJano** [4minitz/4minitz#439]
in version 1.51 the ADD TOPIC (to end of list) isn't working

**Comment by AtJano** [comment]
Hi,

It's a fresh instalation (docker) - with empty DB

**Comment by derwok** [comment]
OK, I tried with a fresh Docker 1.5.1 - "Quick Add Topic" works for me (Mac with Chrome Browser)

1.) First: You know you have to press ENTER key, to trigger the Add functionality?
2.) If you enter some text, then press ENTER what happens? Nothing?
3.) Could you provide us your operating system and browser and version number of browser?
4.) If you know how to open your browser's JavaScript console, please open console and see if there is an error message when you press ENTER on "Quick Add Topic to End of List Field"?

Thankx in advance.

**Comment by AtJano** [comment]
Ok,

1.) It's the Add new topic but to the END of list.
2.) It saves the TEXT ok
3.) Win7 whit Chrome Broswer
4.) I  have restarted the docker and now it works OK
4.a) The look however changed a little, i.e. the icons at the end of line of the topic are now diferent , before they were square ..??? weird

**Comment by derwok** [comment]
Great to hear, it works now.

When the icons ware square, then the "Icon Font" we use was not loaded correctly. So maybe the whole application was not yet loaded correctly in the browser. Maybe the reason for other strange behavior.

We'll keep this issue open for a few more days.
Please comment here, if the problem re occurs.
If not, I will close this issue then.

Thx. & have fun.
(We are in preparatin of bugfix release 1.5.2 - I woulod recommend to wait til this version before using 4Minitz in production).

**Comment by AtJano** [comment]
Off topic question:

is there an IRC channel or mailing list for submitting questions, because it does not make sense via issues/bugs?

**Comment by migerh** [comment]
> Please comment here, if the problem re occurs.

Apparently it didn't reoccur, so I'll close this. Reopen this or open a new issue if the problem came up again.
