### ISSUE TITLE
Info / Action Item can be added several Times

### ISSUE THREAD

**Issue by fd0cwp** [4minitz/4minitz#440]
Hi all,

I have a smaller finding. When you add an info item or an action item to a topic, you confirm the dialog with “save”. When you now click this save button several times, the info or action item is also created several times.

By accident I created an info item twice so I got aware of it. Unfortunately, my finger is quite slow so I made it to create the item only three times. ;-)

I assume that the item should be created only once or is this a hidden mini game? :-)

Best regards, Christoph

**Comment by migerh** [comment]
Wow, you have to be really fast. I can't reproduce this manually, but I can with this small code snippet by pasting it into the command line while having an add info item dialog open:

```js
for (let i = 0; i < 5; ++i) {
    $('#btnInfoItemSave').click();
}
```

Thanks for reporting this!

**Comment by derwok** [comment]
Yes, on *very slow PCs" the UI sometimes is quite slow...
So double triggering is possible...
I just added a "save button disable" immediately after first click on the button.
Let's see what the end-2-end tests say...

**Comment by migerh** [comment]
We might want to consider enabling the button again if something goes wrong. If something does go wrong and the item is not saved the user can only cancel now.

**Comment by migerh** [comment]
Fixed it by re-enabling the button in a `finally` block.
