### ISSUE TITLE
setting email configuration - self-signing certificate error

### ISSUE THREAD

**Issue by Fadlishah** [4minitz/4minitz#443]
**Hi guys, 

I'm new in 4minitz. I have configured the email as below:**

_"//3": "below option configures if and how to send E-Mails",
    "email": {
        "//3.1": "Switch on/off E-Mail sending",
        "enableMailDelivery": true,
        "//3.2": "Choose one of the below mail deliver methods",
        "mailDeliverer": "smtp",

        "//3.3": [
            "defaultEMailSenderAddress: if this is an empty string, the sending users mail address will",
            "be the 'FROM:' sender of the email. If you specify an email address here, this mail address",
            "will be the 'FROM:' sender of each mails, and the sending user will be inserted to the 'REPLY-TO:' field",
            "If you set this to empty, please specify fallbackEMailSenderAddress!",
            "(see admin guide for the decision tree)."
        ],
        "defaultEMailSenderAddress": "noreply@faa.net.my",

        "//3.4": [
            "defaultEMailSenderExceptionDomains: an array of domains.",
            "For these domains the defaultEMailSenderAddress will NOT be used.",
            "Use case: Inside your intranet you want to send mails from real user names of you company.",
            "But if you cooperate with users from other companies inside your 4Minitz, these",
            "users will get trouble sending mail from your 4Minitz to mail addresses",
            "inside their company with their mail address in FROM: header.",
            "This really looks like spam, so it will probably be blocked!."
        ],
        "defaultEMailSenderExceptionDomains": ["faa.net.my", "faa.org.my"],

       "//3.5": [
                "fallbackEMailSenderAddress: if sending user has no mail address specified in the user profile,",
                "this will be 'FROM:' sender.",
                "If defaultEMailSenderAddress is set empty this field must be set with a valid email address.",
                "If this setting is empty and user has no mail address in profile, sending eMail will fail!",
                "(see admin guide for the decision tree)."
            ],
        "fallbackEMailSenderAddress": "noreply@faa.net.my",
        "ignoreSslErrors": true,
        "webSecurity": false,
        "strictSSL": false,
        "allowSelfSignedTLS": true,

        "smtp": {
            "mailUrl": "smtp://username:password@mail.faa.net.my:587/"
        },_

When testing sending Agenda by clicking the SEND AGENDA and check the log, below is the error log.

_*** ROOT_URL: http://1**.1*.0.1**:3100
WebApp current working directory:/4minitz_bin/bundle/programs/server
#Email could not be sent successfully to: user1@faa.org.my
        Email subject: [CSD - Admin Team] Audit Issues (IT & Admin): Procurement on 2018-05-03 (Agenda)
        Error: Error: self signed certificate
#Email could not be sent successfully to: user2@faa.org.my
        Email subject: [CSD - Admin Team] Audit Issues (IT & Admin): Procurement on 2018-05-03 (Agenda)
        Error: Error: self signed certificate
#Email could not be sent successfully to: user3@faa.org.my
        Email subject: [CSD - Admin Team] Audit Issues (IT & Admin): Procurement on 2018-05-03 (Agenda)
        Error: Error: self signed certificate_

**Comment by derwok** [comment]
Is this issue still open on your side?

I'm not an SMTP/TLS expert. And honestly, we most of the time use unencrypted, local SMPT servers. So one shot from my side: If you start 4Minitz via docker, then try the following:
add a `-e "NODE_TLS_REJECT_UNAUTHORIZED=0"` after your `docker run` command.

Please report back if this helps...

**Comment by derwok** [comment]
No feedback.
Nevertheless thanks for reporting!
But we will close this issue for now.
Please reopen, if issue persisist.
