### ISSUE TITLE
Feature Request (UI Multilanguage)

### ISSUE THREAD

**Issue by coldib** [4minitz/4minitz#444]
Hi 4minitz Team,

you made an awesome open source project, thanks for that. I would like to contribute to your work by  adding multi-language to the app.

As this is quite an intensive work I would only take this effort if it's possible to merge the multilang files into your main branch afterwards.

Is this OK for you?

Regards
Wolfgang

**Comment by derwok** [comment]
Hey coldib,
thanks for the positive feedback.

We would be more than happy, if you could take over this big job.
We actually have "translation of UI" on our wishlist for quite some time.
See here: https://github.com/4minitz/4minitz/issues/30 

Maybe you have a look, if this matches your plans roughly?

If yes, I would suggest that we do a Slack session this week to synchronize on where to start...
If you see this helpful, please open https://demo.4minitz.com/  >> About >> Impressum 

and drop an eMail with your contact data to the EMail address specified there. Than we can arrange things.

**Comment by coldib** [comment]
Hi derwork,

will reach out to you as soon as I find some time :)

**Comment by ludovic-durand** [comment]
Hi, I would be interrested in translating the GUI in french .
How could I participate in doing this?

**Comment by jseverinod** [comment]
I can help

**Comment by vmario89** [comment]
i can do the german translations  - also interested in having 4minitz multilang

**Comment by MenDevNL** [comment]
I am willing to do a Dutch translation

**Comment by itrich** [comment]
@ludovic-durand @jseverinod @vmario89 Feel free to support the translation on https://crwd.in/4minitz
