### ISSUE TITLE
Items and Topics are gone unintentionally

### ISSUE THREAD

**Issue by fd0cwp** [4minitz/4minitz#450]
Hi all,

I sometimes have the issue that items or even whole topics unintentionally are gone in a new minutes just because I have forgotten to pin the item or set the topic to re-occurring. To get the information back to the new minutes might be quite some effort.

Would it be reasonable to set the items to pinned and the topics to re-occurring by default when they are created?
It also makes some effort to unpin items / set topics to be no longer re-occurring but my feeling is that it is less effort than getting the info back to the minutes. Additionally, at this point in time you are already where to change the setting by just one click whereby getting back the old information means to leave the context and go to the previous minutes or, even worse, search for it.

BTW: I often click in the item menu on “Edit Item” instead of “Set Pinned” probably because the icons look very similar in shape. Maybe one of them can be changed? Maybe it would be enough already to mirror the edit icon so that the pen and the pin point to different directions.

Best regards, Christoph

**Comment by migerh** [comment]
There is a completed badge now for topics that won't appear in the next minutes. Would this be enough to tell you that you need to make the topic recurring?

![completed](https://user-images.githubusercontent.com/368715/41612247-950e8e3c-73f2-11e8-8016-33717c9a94bd.png)

**Comment by fd0cwp** [comment]
For the topic, this could be fine. But it more often happens that the details are gone. So I would say this "Completed" sign is not enough because it even might not appear because there is an open action item.
