### ISSUE TITLE
Unable to send email via smtp

### ISSUE THREAD

**Issue by 90er** [4minitz/4minitz#460]
Hi,

today i migrated 4minitz from Debian 8 to CentOS 7 (with SELinux enabled).
I also switched from docker run to an docker-compose file - everything is working fine expect sending mails (I migrated the 4minitz_storage folder as tarball and reconfigured permissions and SELinux Labeling).

Do i have to configure an MTA or do you use an library, which doesn't need an MTA? On Debian 8, there was exim configured to just relay to an MS Exchange Server. I managed to configure Postfix on CentOS 7 to also just relay and it works on the command line. When i invite people in 4minitz, there's an tooltip that says, that the email has been send successfully. In tcpdump or postfix, i don't see any traffic.

I already checked SELinux but there are no event.

Thanks for help.

Best regards,
Wolfgang

**Comment by ludovic-durand** [comment]
I am new on 4minitz. Mine is running on docker.
I've configured the 4minitz_settings.json config file.

    "email": {
        "//3.1": "Switch on/off E-Mail sending",
        "enableMailDelivery": true,
        "//3.2": "Choose one of the below mail deliver methods",
        "mailDeliverer": "smtp",
...
        "smtp": {
            "mailUrl": "smtp://your.smtp.server.fr:25/"

**Comment by derwok** [comment]
Hi Wolfgang,
strange, that eMail is not working for you... normally we have very few problesm from this area...
Towards your question: inside our docker image 4Minitz behaves as a MUA (Mail user agent), it will try to connect to an MTA (SMTP server) outside of the docker image. Have you tried to SSH into the running docker image and then `ping`your SMTP server from there?

And: Maybe you could paste your docker compose file here?

**Comment by derwok** [comment]
I hope the problem is gone in the meantime? If not feel free to reopen this issue.
Thanks for your help.

**Comment by 90er** [comment]
Thanks for your help @ludovic-durand and @derwok ,

i figured out, that i my previous collegue had two directories and i copied the wrong configuration file. The problem was the part mailUrl: ... One file was with user authentication and the other one without credentials. It's working now with just the IP-Address and the port.

Best regards,
Wolfgang
