### ISSUE TITLE
send email with Docker and behind a proxy doesn't go

### ISSUE THREAD

**Issue by RedYouMan** [4minitz/4minitz#469]
Hi 
I have used NTLMAP for proxy 
then installed docker
Network 10.0..75.0 and DNS Automatic
My real network is different

I have pulled 4minitz
AI have configured smtp and true
mailurl=smtp://user:psw@smt.gmail.com:587

Agenda shows "OK" for all recipients but log says ECONREFUSED and shows ip of machine of docker

Can you help me?

**Comment by RedYouMan** [comment]
I have also configured proxy in Docker settings

**Comment by derwok** [comment]
Sorry for late answer...
Is this problem still persistent or could you solve it in the meantime?

**Comment by derwok** [comment]
Will close as won't fix.
Please reopen if issue becomes active/interesting again.
