### ISSUE TITLE
Modal-on-Modal breaks scrolling of first modal

### ISSUE THREAD

**Issue by derwok** [4minitz/4minitz#473]
When we show a modal-on-modal and close the later modal, the first modal will not be able to scoll anymore. This is a known bootstrap weakness. See here:
https://stackoverflow.com/questions/28077066/bootstrap-modal-issue-scrolling-gets-disabled

We can reproduce this situation for example with 
* Open the "Create a new action item" dialog
* Reduce browser window height that not the whole dialog fits onto the screen
* Now enter a free-text responsible name that is NOT a valid mail address
* Press enter, so this error confirmation dialog will show up:
![image](https://user-images.githubusercontent.com/4393698/47160952-4ddbc580-d2f1-11e8-98ed-854cf9e22484.png)

* Now Confirm the error message.
* Back to the "Create new Action Item Dialog" user is not able to scroll anymore.
=> OK/Cancel button is not reachable. UI-Dead-End!

Solution would be to improve \client\helpers\confirmationDialog.js with a more clever closing behaviour, to keep the <body> style "modal-open". (see stackoverflow topic above)

**Comment by migerh** [comment]
Alternative solution: Reduce the usage of modals :smile:

**Comment by derwok** [comment]
Should be fixed with PR https://github.com/4minitz/4minitz/pull/474
