### ISSUE TITLE
Feature request: Disable registration

### ISSUE THREAD

**Issue by MenDevNL** [4minitz/4minitz#488]
Hi,

I like your product and I am planning to use is for the meetings of our political party. I have installed it om my home server.
Is it not kind of strange that it is not possible to disable the registrations? I would really like to prevent unwanted users to open an account and start filling my server with their stuff.
So maybe you can consider a setting to disable the registration of new users.

Kind regards,

Menno Manheim

**Comment by derwok** [comment]
Good News!
You can disable self-registration in your settings.json like so
`    "forbidClientAccountCreation": true,`

Then you have to create user accounts as admin.

First: Make yourself Frontend Admin as described here:
https://github.com/4minitz/4minitz/blob/develop/doc/admin/adminguide.md#how-to-become-a-frontend-admin

Second: login with the admin account, then create users via Profile menu / Admin / Create New User.

**Comment by MenDevNL** [comment]
That is indeed very good news! Thank you!

**Comment by derwok** [comment]
Will close issue, as solution was always there...  :-)
