### ISSUE TITLE
[Problem & Feature Request] Login Forbidden & delete account  

### ISSUE THREAD

**Issue by tillchen** [4minitz/4minitz#491]
Hi! 

I encountered a problem when one user's trying to log in for the docker version. It shows login forbidden and I can't seem to find a way to solve this. So I'd really appreciate it if you could help me with this problem. Plus, I'd like to know if it's possible to add the feature of deleting accounts for admins, which I think is really useful:)

Thanks!

**Comment by felixble** [comment]
Hi @tillchen.

First, to your feature request: Currently, it is possible to set a user to inactive. As a frontend admin (see https://github.com/4minitz/4minitz/blob/develop/doc/admin/adminguide.md#how-to-become-a-frontend-admin for details) you can go to "Admin Tasks" and deactivate the user. Then the user cannot log in anymore and he cannot be invited to a meeting series anymore. Completely deleting a user makes it difficult if the user was already part of a meeting series. 

Is this helpful for you?

Now, to "login forbidden" issue: Maybe there is a problem with the users credentials? I would suggest to generate a new password. Unfortunately, this is currently not possible as a "Admin Task". 

Additionally, I just found out that the "forgot password" features uses a different mailing mechanism. Fortunately, the "forgot password" mail will be logged to the server console if smtp mail is not configured. With the following steps you can set a new password for an existing user if you can access the server log:

1) The config `showForgotPasswordLink` must be enabled.
2) Click the link "Forgot your password?" on the login screen and enter the users email address (as a frontend admin you can change the users email address)
3) Take a look at the server log. You should then find something like the following:
```
meteor: I20190407-14:02:38.441(2)? ====== BEGIN MAIL #0 ======
meteor: I20190407-14:02:38.442(2)? (Mail not sent; to enable sending, set the MAIL_URL environment variable.)
meteor: I20190407-14:02:38.453(2)? Content-Type: text/plain
meteor: I20190407-14:02:38.454(2)? From: 4Minitz <4minitz@local.env>
meteor: I20190407-14:02:38.455(2)? To: user@mail.com
meteor: I20190407-14:02:38.455(2)? Subject: [4Minitz] Reset Your Password
meteor: I20190407-14:02:38.457(2)? Message-ID:
I20190407-14:02:38.461(2)?  <>
I20190407-14:02:38.463(2)? Content-Transfer-Encoding: quoted-printable
I20190407-14:02:38.464(2)? Date: Sun, 07 Apr 2019 12:02:38 +0000
meteor: I20190407-14:02:38.466(2)? MIME-Version: 1.0
I20190407-14:02:38.467(2)?
meteor: I20190407-14:02:38.467(2)? To reset your password for user@mail.com visit the following =
meteor: I20190407-14:02:38.470(2)? link:
meteor: I20190407-14:02:38.471(2)?
meteor: I20190407-14:02:38.471(2)? http://localhost:3100/reset-password/Zj0Q-SdRO-f169NpMUSrb5G90BFGTrz=
meteor: I20190407-14:02:38.471(2)? iYi46Epz7q9a
meteor: I20190407-14:02:38.472(2)?
meteor: I20190407-14:02:38.472(2)?  If you did not request to reset your password, please ignore=
meteor: I20190407-14:02:38.473(2)?  this email. If you feel something is wrong, please contact your admin =
meteor: I20190407-14:02:38.473(2)? team
meteor: I20190407-14:02:38.474(2)? ====== END MAIL #0 ======
```
4) Copy the url in the mail. In this example the link is `http://localhost:3100/reset-password/Zj0Q-SdRO-f169NpMUSrb5G90BFGTrziYi46Epz7q9a`. Mind that the character `=` is not part of the link and the output in the second line has to be appended.
5) Open the url in your browser and set a new password

@derwok Maybe we should add a feature to set a new password as an admin?

**Comment by tillchen** [comment]
@felixble Hi! Thank you so much for your reply.

First, I'm aware we have the feature of setting a user as inactive. And I think it might be a good idea to also enable admins to permanently delete one account or change the password for one account if possible.

Second, I can see the content of the email from the log and open the password reset link. However, I still can't reset the password since it shows "Token Expired" error.

Thank you:)

**Comment by felixble** [comment]
I first got the "Token Expired" error, too. The token is the last part of the url (the url consists of `<your-domain>/reset-password/<token>`. Unfortunately, in the log there is a line break in the middle of the token. 

In my case I had to remove the `=` charachter and append the character sequence given in the following line.

**Comment by tillchen** [comment]
@felixble Ah, I see. Problem solved! Thanks:)

**Comment by felixble** [comment]
I am glad you could solve the problem.

What is your use case for deleting a user permanently? How would you handle the case if the user was already part of a meeting series?

For us, a meeting minutes is a document representing a specific situation. We take it very serious that finalized minutes cannot be modified again. The invited users are an important part of the document and the minutes don't tell the truth anymore if we remove an existing user who participated a meeting.

**Comment by tillchen** [comment]
@felixble Ah, I actually I thought this might help if a user can't recover their password and admins can then delete the account and let the user create another new account. But since we can reset the password through the 4minitz log, this feature should be unnecessary:)

**Comment by felixble** [comment]
Ok. Then I will close this issue.
