### ISSUE TITLE
LDAPS and custom certificate

### ISSUE THREAD

**Issue by huguesgr** [4minitz/4minitz#493]
Hello,

Does anyone know how to get LDAPS running with a custom certificate?
Currently, my instance is complaining about not recognizing the certificate chain, and I don't want to enable "allowSelfSignedTLS".

Usually, with OpenLDAP, placing the CA file in `/etc/openldap/certs/` is enough. But here with Meteor I couldn't find how to get it working.
I also tried `/etc/ssl/certs/`, same result.

**Comment by derwok** [comment]
Hi,
Thanks for trying 4Minitz.
4Minitz uses the LDAP client by ldapjs.org. If you have a valid certificate, you normally dont have to do anything on client side - only specify ldaps:// as URL. ldapjs does secure connection via node.js SSL architecture. In the node js doc we find [this quote](https://nodejs.org/api/tls.html#tls_tls_createsecurecontext_options):
> Default is to trust the well-known CAs curated by Mozilla.

So if you tried ldaps:// and got this error, then you probly don't have it signed by a "well known CA". First suggestion would be to get a Let's Encrypt certificate then?

If this is not possible, then unfortunately, I don't think 4Minitz is able to connect via ldaps:// currently - sorry for that.

# Possible Future Solution on our side
See:
* http://ldapjs.org/client.html tells us that we have to pass `tlsOptions` as node.js wants them 
* https://nodejs.org/api/tls.html#tls_tls_createsecurecontext_options tells us that we can pass filenames to the CA cert chanin here in an options object as keys

So, maybe a future solution could just hand-over these `tlsOptions` from 4Minitz `settings.json`to when we call the ldap module's `ldap.createClient`

@migerh maybe you comment on this?

**Comment by huguesgr** [comment]
Thank you for your answer.
Here this is for a large company which uses it own, internal, root certificate authority.
Indeed it would be nice to be able to pass to ldapjs the root certificate path.

**Comment by migerh** [comment]
Hi @Wohlraj 

You may want to give [NODE_EXTRA_CA_CERTS](https://nodejs.org/api/cli.html#cli_node_extra_ca_certs_file) a shot. If you do, please tell us if it worked or not so we can add this to our docs.

**Comment by huguesgr** [comment]
Hi,

Added an environment variable to my `docker-compose.yml`:
`NODE_EXTRA_CA_CERTS=/etc/openldap/certs/REDACTED.cer`
Set `allowSelfSignedTLS` back to false, and everything works fine :)

I double-checked by removing this variable and checking that it fails.

Thank you!

**Comment by migerh** [comment]
Thanks for checking it out! I extended our admin guide with this information: #497
