### ISSUE TITLE
4minitz can't setup email agenda to work, it sais that mail delivery is not installed

### ISSUE THREAD

**Issue by Ske87** [4minitz/4minitz#494]
Hi all,
I'm new to github, i tried 4mintiz but i have problem configuring it to send agenda via gmail, it sais that mail delivery is not installed, so i think to config is problem, i appriciate any kind of help or suggeston how to solve this issue

Best regards,

Nebojsa

**Comment by derwok** [comment]
Could you please copy & paste your personal  `settings.json`? (Don't forget to replace any passwords with XXX)

**Comment by derwok** [comment]
Closing this item after 11 days.
If the problem still persists, please re-open this topic.

**Comment by elkham** [comment]
Hello,
 i have the same problem, i configured smtp in my settings.json file (under docker) 
 but i still have the error : Error Email delivery is not enabled in your 4minitz installation. 
did i miss something ?

Regards,
Mirco

**Comment by BigSnicker** [comment]
I think I ran into that problem when I accidentally missed setting

"enableMailDelivery": true,

**Comment by wasimss123** [comment]
Hi Even after enabling the mail delivery true still it shows the error.

"enableMailDelivery": true,


Can anybody help me to fix this
