### ISSUE TITLE
slow interface / "you are using a pure-JavaScript implementation of bcrypt"

### ISSUE THREAD

**Issue by huguesgr** [4minitz/4minitz#500]
Hello again,

When firing up the Docker container, this message is shown in the logs:

> Note: you are using a pure-JavaScript implementation of bcrypt.
> While this implementation will work correctly, it is known to be
> approximately three times slower than the native implementation.
> In order to use the native implementation instead, run
> 
>   meteor npm install --save bcrypt
> 
> in the root directory of your application.

Actually, the interface is very slow. Is it related to this message?
However, I do not know how to run that `meteor npm install` command in the container: not sure if that's even possible.

Any help is appreciated :)

**Comment by huguesgr** [comment]
Anyone?
The online demo server is perfectly fine and fast, is anyone currently running 4minitz in Docker without my issues?

**Comment by derwok** [comment]
Hi. 
This is probably not bcrypt. Bcrypt is only for login Passwort handling. 
Do you use LDAP? If yes. How many users are imported. There is a known performance issue. 
What browser do u use? How many meetings and minutes are in DB?

**Comment by derwok** [comment]
You May also try to use the most recent unstable version from docker.  But please as separate staging testing version. In a separate directory.

**Comment by huguesgr** [comment]
I performed some more testing this morning:

- separated mongodb in another container -> no change
- switched from 4minitz:latest to 4minitz:develop container -> no change

However I just noticed that there is no issue when creating a new, empty meeting series.
So it might have something to do with how many topics and items there is in one meeting series.
So far I have 30 topics and a total of 73 action of info items.

**Comment by huguesgr** [comment]
any news?

**Comment by migerh** [comment]
What exactly is slow? What exactly are you doing that is slow (e.g. creating a new topic or scrolling the minutes page etc.)? What browser are you using?

I just checked one of my production meetings and there are 42 topics and a total of over 100 action/info items. So that should not be an issue.

**Comment by huguesgr** [comment]
Everything related to edition is slow: creating a topic, adding a detail, etc.
Navigation/scrolling is normal. Using Firefox 60 ESR and latest IE version.
I'll post a video/gif in a few days if that can be helpful.

**Comment by derwok** [comment]
Can not reproduce it. Multiple browsers, mutiple OSes.
Will close issue. Please reopen if way to reproduce occurs.
