### ISSUE TITLE
smtp issues

### ISSUE THREAD

**Issue by TheRich-71** [4minitz/4minitz#507]
Hi,
I am using the stable docker version of 4minitz at a Synology Diskstation. So far it seems to work, but emails cannot be sent via smtp.
Setting:
> "mailUrl": "smtp://MAILUSER:PASSWORD@MAILSERVER:587/"

Error Message:
> meetingseries.update: []
> #Email could not be sent successfully to: User@mydomain.com
>	Email subject: [4Minitz] Your role has changed for MEETINGNAME
>	Error: Error: getaddrinfo ENOTFOUND MAILUSER MAILUSER:587

Any hints how to find the error? I tried the same with smtps and port 465, with same result. Ping to the mailservers address works fine from within 4minitz docker instance, so server seems to be reachable...

**Comment by TheRich-71** [comment]
Could it be, that the password causes a mistake due to special characters? I read something [here](https://stackoverflow.com/questions/24093421/meteor-email-not-working-error-getaddrinfo-enotfound), but the solution proposed there using encodeURIComponent did not work on first attempt (server is not starting again). Is there any possibility to escape the password characters?

**Comment by TheRich-71** [comment]
Trial and error resolved: It is the password. In the current stable docker image (v. 1.5?), avoid special characters in your smtp password, then it works (might get difficult in some institutions, though).

**Comment by derwok** [comment]
Thx. for reporting and solving.
Currently no idea why special characters make problems here?
Could you give one example?

**Comment by TheRich-71** [comment]
Hi,
my old password was `1+$?htHq$NXb` (it is used nowhere else any longer, so safe to post it here...). I did not try which character puzzles the system, but it does...
