### ISSUE TITLE
Skip a single action item instead of the whole topic

### ISSUE THREAD

**Issue by itrich** [4minitz/4minitz#509]
Hi all,

I'm about to introduce 4minitz and we ran into the following problem:

If a topic consists of multiple action items under which one of the action item has a due date in the distant future, it is not possible to only skip the corresponding action item, but only the whole topic. Imagine the following scenario:

**Topic A**
  |__ Action Item 1 due to next month
  |__ Action Item 2 due to next year

In the next meeting agenda I want to discuss about the progress of action item 1, but I don't want to have action item 2 on the agenda.

Maybe there should be an option for action items "Skip until x days before due date".

**Comment by derwok** [comment]
Thanks for this suggestion...

The current concept behind the action item due date is, that work can start immediately and in every meeting we want to report progress. If nothing new to report, then the "eye" can scip quite fast. Nevertheless experience shows: action items have a greater chance to get done, if we regularly look at them.

So a due-date gives no clue, when and for how long an AI shall be skipped.
Automatically skipping would need a "start date" that we don't have.

For manual skipping, as you suggest, currently I see not a high pressure (From years of actively working with 4M). But I might be wrong.

So, we'll keep this issue open for some while and see if others give a "Thumb up".
