### ISSUE TITLE
SMTP error on annonymous Relay(Exchange)

### ISSUE THREAD

**Issue by ghost** [4minitz/4minitz#510]
Hi,
 I installed the latest docker version recently. I try to setup smtp for our local exchange server, which allows anonymous SMTP in the LAN. I tried different settings, ports, also with or without user names and passwords, but I always get the error 

```
#Email could not be sent successfully to: user@xxx.xx
        Email subject: [XX] XXXXXXXXXX (Agenda)
        Error: Error: unable to verify the first certificate

```
I would expect the following setting to work:
```
"smtp": {
	"mailUrl": "smtp://exchange.xxx:25/"
},
```
Any help would be appreciated,
Matthias

**Comment by itrich** [comment]
You can disable certificate verification by setting the environment variable: `NODE_TLS_REJECT_UNAUTHORIZED=0`

To do this, either add the above given line to a file and pass it to `docker run` via `--env-file` or add it directly as an argument via `--env NODE_TLS_REJECT_UNAUTHORIZED=0`

**Comment by itrich** [comment]
I just found out that NODE_TLS_REJECT_UNAUTHORIZED is set via the configuration entity allowSelfSignedTLS within the LDAP setting group. See `imports\ldap\import.js`:

```
let allowSelfSignedTLS = ldapSettings.allowSelfSignedTLS;
selfSignedTLSAllowed = process.env.NODE_TLS_REJECT_UNAUTHORIZED;

if (allowSelfSignedTLS) {
        process.env.NODE_TLS_REJECT_UNAUTHORIZED = 0;
}
```

Thus, you can alternatively set {  "ldap": {"allowSelfSignedTLS": true } } in order to deactivate certificate verification.

**Comment by ghost** [comment]
For some reasons your final comment ist missing, from @itrich the final solution:
The setting
`{ "ldap": {"allowSelfSignedTLS": true } } `
worked!
Thank you

> I just found out that NODE_TLS_REJECT_UNAUTHORIZED is set via the configuration entity allowSelfSignedTLS within the LDAP setting group. See imports\ldap\import.js:
```
let allowSelfSignedTLS = ldapSettings.allowSelfSignedTLS;
selfSignedTLSAllowed = process.env.NODE_TLS_REJECT_UNAUTHORIZED;
if (allowSelfSignedTLS) {
        process.env.NODE_TLS_REJECT_UNAUTHORIZED = 0;
}
```

> Thus, you can alternatively set { "ldap": {"allowSelfSignedTLS": true } } in order to deactivate certificate verification.

**Comment by itrich** [comment]
Glad to have helped. I deleted my second comment (which you cited), because after further investigation I found out that the corresponding function is only called if and only if `GlobalSettings.getImportUsersOnLaunch()` or `GlobalSettings.hasImportUsersCronTab()` is true. Hence, my comment may be misleading for a setup without LDAP.
