### ISSUE TITLE
[Question] Are LDAP groups usable to add members?

### ISSUE THREAD

**Issue by TheRich-71** [4minitz/4minitz#512]
Hi, at the moment we can import only persons from LDAP as users. I think, for some purpose it might be interesting to add all members of a LDAP-group to a meeting. Would this be possible now, or could it be added as feature request?

**Comment by xlxs4** [comment]
My team would also be interested in that

**Comment by derwok** [comment]
Hey, 
sorry - this is currently not supported / planned.
While I think I get the idea / benefit. It will also raise some complex edge cases on LDAP import: 

* what if a user is removed from one group and added to another one... so we would need a rather cumbersome merging process of groups. 

* As LDAP groups can contain also sub groups, this will lead to hierarchical tree climbing...

If your'e talking of using LDAP groups for meeting invitations it gets even more complicated
* Assume a meeting minute is not finalized. In parallel the admin changes the LDAP groups members. When do we check that group's members? On minute create? On minute finalize? 

So: sorry - currently not planned. 
But feel free to reopen this issue in parallel to a pull request, if you like.  :-)
