### ISSUE TITLE
Why only Admins can see full names?

### ISSUE THREAD

**Issue by TheRich-71** [4minitz/4minitz#513]
I was asked by my users, if it would be possible to show the full names of the users while adding them to the participants list. If I log into 4minitz and create a new meeting series, I get "username - long name" shown in a hoverbox while adding participants. Users without Admin role see only the username, which is not necessarily self-explaing. The same applies to meeting minutes, where normal users see only their own long name and all others as username.
If I can change this behavior, please let me know how...

**Comment by derwok** [comment]
It sounds like you eventually set 
trustedIntranetInstallation To false in your settings.json?

Could you please check?

**Comment by TheRich-71** [comment]
Yes, you are right, I had this setting at false due to the privacy issue of sending all email addresses around. Probably a bit too much function in one setting?
