### ISSUE TITLE
Select2 placeholders are not shown with jquery 3.3.x

### ISSUE THREAD

**Issue by itrich** [4minitz/4minitz#515]
As already noticed in https://github.com/select2/select2/issues/5585, the placeholders (Select...) of the _Labels_ and _Responsible_ select2 fields are not shown initially.

![Bildschirmfoto vom 2019-10-30 19-12-13](https://user-images.githubusercontent.com/29982899/67886142-3e6c9a80-fb49-11e9-9b5d-6d880ec7dd70.png)

Keep an eye on https://github.com/jquery/jquery and https://github.com/select2/select2 respectively, for a fix of this issue.

**Comment by itrich** [comment]
Should we implement the workaround suggested in the above linked issue for version 2.0?

**Comment by derwok** [comment]
Yeah. Feel free to give it a shot and see if it works. 
https://github.com/openculinary/frontend/pull/10/files
