### ISSUE TITLE
Consider linking 4Minitz landing page to buymeacoffee.com

### ISSUE THREAD

**Issue by 4MinitzMarketingConsultantNo1** [4minitz/4minitz#518]
Thereby you could offer your users a fun and simple way to express their gratitude and support your work.
Best regards,
your marketing department

**Comment by derwok** [comment]
Wow, what a great idea.
Good work, marketing department!
We'll consider this.

**Comment by derwok** [comment]
Closed with commit [037822b0](https://github.com/4minitz/landingpage/commit/037822b0b02bb2e76cfca08a8f0aff8fe3f8f6d3)
