### ISSUE TITLE
importOnLaunch results in pattern must be a string!

### ISSUE THREAD

**Issue by shemgp** [4minitz/4minitz#543]
Hello,
I want to use sAMAccountName as the username but if I try to enable importOnLaunch or importCronTab it errors out with:
```
/opt/4minitz/4minitz_bin/bundle/programs/server/node_modules/fibers/future.js:280
                                                throw(ex);
pattern must be a string!
```
Could you please help/guide me? Thanks.

**Comment by derwok** [comment]
Hi, 
sorry to hear you got problems setting um 4Minitz.
Some questions:
1. if you disable ldap, everything works fine?
1. if its only LDAP enabled that causes problems, could you pls. copy & paste your LDAP configuration?
1. Couls you please copy & paste more context lines from the console? We need the whole exceptions stack trace.

Thx. WOK

**Comment by shemgp** [comment]
Hello,
Here are the answers to your questions:
1. Yes it works when disabling ldap
2. [settings.json.txt](https://github.com/4minitz/4minitz/files/4450396/settings.json.txt)
3. Here's the output: 
```
Importing LDAP users on launch. Disable via settings.json ldap.importOnLaunch.
Configuring cron job for regular LDAP user import.

/opt/4minitz/4minitz_bin/bundle/programs/server/node_modules/fibers/future.js:280
						throw(ex);
						^
pattern must be a string!
```

By the way, I just realized that `importOnLaunch` works, but `importCronTab` doesn't.

**Comment by derwok** [comment]
OK. I see the problem: 

You can't just switch the  `importCronTab` from false to true (see the [4Minitz Admin guide](https://github.com/4minitz/4minitz/blob/develop/doc/admin/adminguide.md)). To perform regular imports (e.g., every night at 05:14 AM) you must give a **cron compatible string**. 
See example in the [LDAP section in the admin guide](https://github.com/4minitz/4minitz/blob/develop/doc/admin/adminguide.md#available-configuration-options) or more explanation on [the cron tab page](https://github.com/node-cron/node-cron#cron-syntax). 

Eg. try something like: `"importCronTab": "* 14 5 * * *",`

Additionally I see two LDAP setting values that we do not support:
```
	"bindWidth": "dn",
	"searchDn": "dn",
```
plz consider to delete them.

Have fun.
WOK.

**Comment by shemgp** [comment]
It works. Thanks.
