### ISSUE TITLE
language cannot be changed

### ISSUE THREAD

**Issue by MrCardigan** [4minitz/4minitz#561]
Hey, 4minitz is great but I cannot manage to change the UI language. I tried a local docker on linux and a docker on a synology NAS (http://139.14.4.157:3100). No matter which platform or browser I use, the language is always english and a cannot find a setting to change this. Is there a solution for this?

**Comment by derwok** [comment]
Hey, great you like 4Mintz. The current stable version v1.5.2 is only available in English.
We are preparing a version 2.0 (that will still take some time) with multi-language support.
You may check here on translation progress: 
https://crowdin.com/project/4minitz
(The first percentage value is state of machine translation, the second percentage number is state of native speaker review and corrections).

If you want to try out the current development state, use the development test server here:
https://develop.4minitz.com/
Or install the docker "unstable" image.

Feel free to re-open this issue if you have language switching problems with the current development version.

**Comment by MrCardigan** [comment]
Thank you @derwok for your answer. I managed to set up version 2.0 though I really struggled with mongodb ;).

The login screen does show up in the selected language, but the toolbar and everything when I am logged in, stays in english. Do you have any idea what may cause this issue?

**Comment by derwok** [comment]
Pre-Login we cannot store your language preference.

Once you logged in you can change language via User Menu / Set Language.

Then we'll store it for the future for this user (when user is logged in).

Best way is to set in your browser settings your generally preferred 
language. This browser setting we'll use first if user has not specified 
anything else.

WOK

**Comment by itrich** [comment]
Hi @MrCardigan,

have you configured the ROOT_URL within your [settings.json](settings_sample.json) correctly? Your browser will try to download the translations from the given ROOT_URL and hence fails if ROOT_URL is not reachable.

Best wishes,
Eduard

**Comment by MrCardigan** [comment]
Thank you @derwok & @itrich ,
I'm new to git and did not expect more answers, if I delete my comment :). In fact I just recognized the ROOT_URL setting after I commented again 🙈 . That solved the Problem
