### ISSUE TITLE
Create Tab "Items" on meeting series view

### ISSUE THREAD

**Issue by derwok** [4minitz/4minitz#58]
### As a invited user of a meeting series I want to have a non-hierarchical view an all created items of the meeting series.
- [x] Next to tabs "Minutes" & "Topics" create a tab "Items" 
- [x] "Items" tab shows all ActionItems and InfoItems without(!) their parent topic
- [x] Create filter bar with "Type: Action/Info", "State: open/closed" and free-text search in the subject.
- [x] If Item has labels, entering "#label" into free-text search allows to find items with this label
- [x] If Item has responsibles, entering "@[responsible]" into free-text search allows to find items with this responsible (without brackets ;-)
- [x] Extend free text search to allow searching in more field than only the subject

Additional ideas:
- [x] Make search case-insensitive
- [x] Allow Tag-Search with substrings, so e.g. "#Dec" should show all "#Decisions"
- [x] Provide a small dropdown menu (arrow left of search entry) that gives menu items for the below options. Click on menu items closes menu and inserts according text to beginning of search text (with space at end)
    - [x] Action Item
    - [x] Info Item
    - [x] Open
    - [x] Closed

**Comment by felixble** [comment]
I moved the following ACs into a separate story:

* [Items are sorted by time-stamp of last change](https://github.com/4minitz/4minitz/issues/154)
* [Place info icon at the right side of the filter input field which opens an info dialog by on click. This info dialog shows hints how to use the filter efficiently](https://github.com/4minitz/4minitz/issues/155)

**Comment by felixble** [comment]
Closed with 737a8d209875e013ccbaec269af97d826e9315bd
