### ISSUE TITLE
Selection of Responsible(s) for Topics & ActionItems

### ISSUE THREAD

**Issue by derwok** [4minitz/4minitz#61]
### As a moderator I want a fast way to select the responsible(s) for an ActionItem to save everybodys time
- [ ] Offer drop-down on "Edit/Add AI" dialog
- [ ] Offer drop-down on minutes view
- [ ] Drop-down lists all participants with checkboxes
- [ ] Checkboxes add/remove users to the responsible list of this AI

**Comment by felixble** [comment]
Maybe we could use the bootstrap-select library from silviomoreto: https://silviomoreto.github.io/bootstrap-select/examples/#multiple-select-boxes. There is also an atmosphere package available: https://atmospherejs.com/leeb/bootstrap3-select. The library itself is published under the MIT-License.
