### ISSUE TITLE
Send EMails for validation / reset Password

### ISSUE THREAD

**Issue by felixble** [4minitz/4minitz#63]
As an admin I want to be sure that people register with a correct email Address to avoid having "anonymous" users in my accounts collection.

see: 
* https://themeteorchef.com/snippets/sign-up-with-email-verification/
* https://docs.meteor.com/api/passwords.html#Accounts-sendVerificationEmail

- [ ] Activate `sendVerificationEmail` for new registered users
    - [ ] When admin registers new user, no such mail should be sent!
- [ ] Also activate `sendResetPasswordEmail` for users that forgot their password.
    - [ ] Consider LDAP users! They can not get a "reset password" mail
    - [ ] De-Activated users should not be able to reset password

No E2E needed here

**Comment by derwok** [comment]
https://themeteorchef.com/snippets/sign-up-with-email-verification/

**Comment by migerh** [comment]
Added to the Hello World milestone as this is very important to have until then.

**Comment by iCatCat** [comment]
3d

**Comment by derwok** [comment]
Missing: LDAP acceptance criteria
