### ISSUE TITLE
First minute of a series is not reactively visible

### ISSUE THREAD

**Issue by felixble** [4minitz/4minitz#7]
If you add the first minute to an empty series it will be not displayed until you reload the page:
 - Create a new meeting series
 - Open details page of the new meeting series and click the "add minutes" button
 - Click on the name of the meeting series in the headline to go back to the details page of this series
 - The table of minutes remains empty until you reload the page

**Comment by derwok** [comment]
Yes, we will go for "Solution#2" of this article:
https://www.discovermeteor.com/blog/reactive-joins-in-meteor/
I will take care...

**Comment by derwok** [comment]
Should work now on develop/ branch.
Clsoing #7
