### ISSUE TITLE
Skip Topics

### ISSUE THREAD

**Issue by derwok** [4minitz/4minitz#75]
As a moderator I want to prepare a meeting, but skip some (automatically added) topics to focus my meeting on other topics.

- [x] On non-finalized meetings it is possible to mark/un-mark a topic as "skip".
- [x]  Menu: "glyphicon-eye-close Set Skip" / "glyphicon-eye-open Unset Skip"
         after "Set Recurring". 
- [x] A skipped topic is not included in "agenda mails" / "finalize" InfoItem & ActionItem mails
- [x] A skipped topic shows the "glyphicon-eye-close" next to the "..." menu button
- [x] A skipped topic's subject is displayed with strike-through font style
- [x] Nevertheless it is possible to edit a skipped topic (add II, add AI, delete topic, ...)
- [x] A skipped topic will automatically be opened and its checkbox is disabled
- [ ] A skipped topic should only be visible for moderators
- [x] A skipped topic will show up in the next meeting as non-skipped
- [x] A skipped topic will show "as normal" in the meeting series "all time topics" list
- [x] The filter "Hide closed topics" should also hide skipped topics
- [x] Add E2E test (check sent EMails)
- [x] Update UserDoc

**Comment by iCatCat** [comment]
4d

**Comment by derwok** [comment]
Done!  ;-)
