### ISSUE TITLE
Drop-down menu for Topic / InfoItem / Action items

### ISSUE THREAD

**Issue by derwok** [4minitz/4minitz#8]
As a user I want to have a drop down menu for actions I can do with topics and info items to improve my visual impression of 4Minitz and to clarify & speed up my work flow.

- [x] **Topic** should get toolbar (3 dots) button with drop down menu: 
   - Add Info Item
   - Add Action Item
   - -----------------------
   - Edit
   - (Un)Set Recurring
   - Delete
- [x] **Action/Info Item** should get toolbar button with drop down menu
   - Add Details
   - -----------------------
   - Edit
   - (Un)Set Sticky
   - Delete
- [x] Remove "old" icons
- [x] New menu should get some nice "hover" effect
- [x] Remove "Action Item" / "Info Item" radio button from the modal dialog.
- [x] Show Recurring & Sticky icon outside of drop down menu, if state is set to "TRUE"
- [x] Click on recurring / sticky icon sets state to "FALSE".
- [x] Adapte E2E tests
- [x] Adapt README.md screen shot
- [ ] Adapt User Doc

**Comment by derwok** [comment]
I've seen @librue (Lisas) approach on branch /ui-split-add-element-button. I really like the shorter click path and the direct clarity what happens! Unfortunately it tends to fill the UI with loads of "highly visible" buttons.

Is there a way to either
* hide the buttons and only show them on a mouse-enter to the topic or
* make the muttons very subtle, nearly invisible and then bring them to normal color on mouse enter to the topic?
![additem](https://cloud.githubusercontent.com/assets/4393698/15600575/1e492342-23eb-11e6-9dde-7701d48e04a0.png)

**Comment by felixble** [comment]
@derwok that's a valid objection. Maybe we could use a floating action button which can "fling out" the actions "add information" and "add action item"? Have a look at the "Speed dial" transition described here: https://www.google.com/design/spec/components/buttons-floating-action-button.html#buttons-floating-action-button-transitions.

We should consider that we cannot use the "on mouse enter" event on touch devices.

**Comment by librue** [comment]
@derwok and @felixble: Yesyesyes, you are right, the buttons are much too big and prominent. I just added them the way they are now so that @felixble can wire them. I'm thinking about a better solution...
